### ISSUE TITLE
Combine ODataRouteAttribute and RouteAttribute, HttpGetAttribute, etc

### ISSUE THREAD

**Issue by xuzhg** [OData/AspNetCoreOData#101]
Let's consider to use [RouteAttribute], [HttpGetAttribute] as OData attribute routing template provider.

**Comment by magneticcore** [comment]
Hi @xuzhg ,

Let's set a BooksController (with book entity including a field named PressId and its general route /api/books) contening an OData function GetBookByPressId.

With your consideration, what will be the corresponding RouteAttribute of the current OData tag on the BooksController OData function:
[ODataRoute("GetBookByPressId(PressId={pressId}")]
public async Task<IQueryable> GetBookByPressId(int pressId) { ... }
.

**Comment by xuzhg** [comment]
@magneticcore I am thinking to support the following: (Please share your thoughts)

```C#
[Route("odata")
public class BooksController : Controller
{
    [HttpGet("GetBookByPressId(PressId={pressId}")]
    public async Task GetBookByPressId(int pressId) { ... }
}
```

```C#
// [Route("odata")
public class BooksController : Controller
{
    [HttpGet("~/odata/GetBookByPressId(PressId={pressId}")]
    public async Task GetBookByPressId(int pressId) { ... }
}
```

**Comment by magneticcore** [comment]
Let's speak about routing for the GetBookByPressId function with your examples

To add an OData model, the function AddModel("odata", GetEdmModel()) is used. So "odata" path is prefixed for the routing.
I add a third possibility of coding BooksController:

```
[Route()]
public class BooksController : Controller
{
    [HttpGet("GetBookByPressId(PressId={pressId}")]
    public async Task GetBookByPressId(int pressId) { ... }
}
```

With the three possibilites of BooksController below and taking into account the routing prefix given in AddModel, named afterwards "model prefix", the routings for the endpoint function GetBookByPressId can be (with https://localhost/):

1. https://localhost/odata/odata/GetBookByPressId(PressId=2) -> the model prefix is prefixed to the Route("odata") from class BooksController, giving the path odata/odata
2. https://localhost/odata/GetBookByPressId(PressId=2) -> The model prefix is ignored because the route given for GetBookByPressId is absolute with ~/ in HttpGet()
3. https://localhost/odata/GetBookByPressId(PressId=2) -> the model prefix is used only because Route() from BooksController gives no path, so the path is just odata.

**Comment by xuzhg** [comment]
@magneticcore I have an implementation now, would you please take a look and share me your thoughts, you can try the sample at: https://github.com/OData/AspNetCoreOData/tree/master/sample/ODataCustomizedSample

**Comment by magneticcore** [comment]
@xuzhg I will look your sample.

Concerning the tought on routing, is there already some changes in OData nightly build?
On our pseudo or development project, for example, a function [HttpGet("GetPressesFromBook(PressId={pressId])"] or action [HttpPost("CalculateRate")] work without [ODataRoute] tag

**Comment by xuzhg** [comment]
No, it should be in the nightly after my commit

**Comment by dxrdxr** [comment]
I would like to add in my opinion on the specific case of the prefix that is set in `AddModel`, aka _model prefix_.

When using convention based routing it is pretty clear that the _model prefix_ is used in the route templates, it acts like an implicit `[Route("odata")]`. 

When switching to Attribute routing I discovered through trial and error that I needed `[HttpGet("odata/Contacts({key})/MyAddress")]`, conceptually that seems wrong as I already specified the _model prefix_.

In my particular use case, for almost all actions the convention models are what I need. And for the specific exception case I added an Attribute route. But I needed to explicitly add the _model prefix_ in each action, this is messy if I ever need to change the prefix (e.g. versioning) as it is spread throughout the many controllers. I could use the `RouteAttribute` on the controller to minimize the duplications, but using `[Route("odata")]` will (rightfully) cause a double "odata" in the convention routes which is not desirable.

Like the 3 examples above I would suggest a slightly different interpretation.

- If there is no RouteAttribute then the _model prefix_ is always used for **both** convention and attribute routes.
- If there is a RouteAttribute ( or HttpGet()) with an absolute path the _model prefix_ is ignored.
- If there is a RouteAttribute with a value, then the _model prefix_ is prefixed to the route (possible looking like double prefix), consistent with the overall ASP.Net Core model.
- If there is a RouteAttribute with a string.empty value, then it is interpreted as "/" and the _model prefix_ is prefixed to it.
- If there is a RouteAttribute `[Route()]` then this is an error as ctor `RouteAttribute(null)`  is invalid.

Or as a summary, if you don't want the model prefix you must use an absolute path, otherwise it follows the ASP.Net Core routing model with the OData model prefix prepended.

**Comment by xuzhg** [comment]
@dxrdxr Thanks for sharing your opinion.

Like the issue title mentioned, I want to use the existing ASP.NET Core attributes for OData attribute routing. 
Here's my thoughts (for attribute routing):

1) Most of ASP.NET Core customers understand [RouteAttribute], but not the route prefix.  
2) I think attribute routing is the routing that "what you see from the route template is what you can call." That is what you see from [RouteAttribute] and [HttpGetAttribute], etc, is what you can call from client.
3) If we implicitly apply model prefix (behind the scene), that's conventional rule. 

However, nothing is certain. I'd like to get more feedbacks from community.

**Comment by xuzhg** [comment]
ODataRouteAttribute is gone in the 8.0 rtm release and replaced to use RouteAttribute, HttpGetAttribute, etc.
