### ISSUE TITLE
ASP.Net Core OData 8 and Swagger Query Options/Parameters Not Shown

### ISSUE THREAD

**Issue by gbraven-dev** [OData/AspNetCoreOData#1029]
I've created an ASP.Net Core OData 8 service and enabled Swagger generation and the Swagger UI however my OData endpoints do not show any query options in the Swagger UI.

All query options are enabled globally per below:
builder.Services.AddControllers().AddOData( options => options.EnableQueryFeatures().AddRouteComponents( "odata", modelBuilder.GetEdmModel(), builder => builder.AddSingleton<IODataSerializerProvider, CustomODataSerializerProvider>()));

Get() methods returning IQueryable(s) on my controllers are labelled with the [EnableQuery] atteibute.
I am able to successfully execute all standard OData queries against my entity sets (filter, select, order by, etc)
However the list of query options in Swagger UI is empty (no query parameter are shown in the Swagger generated spec for the API either). Is this a known issue? I've seen reports of this behavior in earlier versions of ASP.Net Core and OData (and some workarounds based on customizing Swagger behaviors with a custom operation filter), but my understanding is this is supposed to work in the latest ASP.Net Core/OData versions. Thanks for any insight.

**Comment by DimaMegaMan** [comment]
It's not a bug, currently, the OData team doesn't support Swagger documentation at all and you will get many bugs with generated OpenApi doc (for example with string parameters without '', OdataQueryOptions, and so on), because it was rendered without knowledge about OData model, but you are lucky boy 😉, a few months ago it was supported by https://github.com/dotnet/aspnet-api-versioning (don't be confused about the name, it also works without API versioning at all), it provides the possibility to document your OData API, using OpenApi scheme, there are few examples, I would say that it's simply the best solution for OData Api documentation it's not perfect but it solves a lot of problems, GL HF😉

**Comment by gbraven-dev** [comment]
Thank you.  I looked at aspnet-api-versioning previously as a possible solution, but I assumed it likley got its support for generating specifications/swagger page with OData query parameters from ASP.Net Core/OData.  The examples and documentation in aspnet-api-versioning indicated I would have to do some refactoring to integrate it so I backed away given the uncertainty I had that it would solve the problem.

I integrated and hid the versioning (not needed yet) using APIVerisionNeutral attributes on my controllers and was able to get the OData query parameters into the generated spec and swagger pages.  One quirk -- if all of my controllers were attributed as version neutral the odata root and $metadata pages were not accesible (no routes resulting in 404s).  If at least one controller was not attributed as APIVersionNeutral they became accessible/routable again.  Somewhat strange, haven't run to ground.

Appreciate the input, gave me the confidence to push through doing the refactoring that was required.

Thanks.
