### ISSUE TITLE
OData Query parameters are not working in 8.2.3

### ISSUE THREAD

**Issue by itsmegopi** [OData/AspNetCoreOData#1152]
We have migrated our API from 2.2 to 6.0 and we are upgraded OData also to 8.2.3. 
Before update custom methods with query parameters are working well but after update no luck.
Basic OData methods and functionalities are working well and good after update too.

Below is my controller code.

```
public partial class DepartmentController : ODataController
 {
	[HttpGet, Route("api/v1/department/getDepartmentsByCompany")]
	[Microsoft.AspNetCore.OData.Query.EnableQuery]
	public Task<BaseResponse<IEnumerable<Department>>> GetDepartmentByCompany([FromQuery] int id, [FromQuery] FunctionalType? functionalType)
	{
		try
		{
			return "success data";
		}
		catch (Exception ex)
		{
			LogHelper.LogException(ex, _hostingEnvironment);
			return "Failed";
		}
	}
	
	[Microsoft.AspNetCore.Mvc.HttpGet] 
	[Microsoft.AspNetCore.OData.Query.EnableQuery]
	public System.Threading.Tasks.Task<System.Collections.Generic.IEnumerable<Department>> Get()
	{
		return _implementation.GetAllAsync();
	}
	
    [Microsoft.AspNetCore.Mvc.HttpGet]
	[Microsoft.AspNetCore.OData.Query.EnableQuery] 
	public Microsoft.AspNetCore.OData.Results.SingleResult<Department> Get(int key)
	{
		return _implementation.GetAsync(key);
	}
 }
```
And Program.cs looks like 

```
builder.Services.AddControllers(g =>
{
    g.EnableEndpointRouting = false;
}).AddOData(opt =>
    {
        var batchHandler = new DefaultODataBatchHandler();
        opt.AddRouteComponents("api/v1", DIRegister.GetEdmModels(), batchHandler);
        opt.Count().Select().Filter().OrderBy().Expand().SetMaxTop(int.MaxValue);
        opt.EnableQueryFeatures(int.MaxValue);
        opt.EnableAttributeRouting = false;
    }).AddJsonOptions(g =>
    {
        g.AllowInputFormatterExceptionMessages = true;
    });
```
I am getting below exception 

    The key value (getComapnyByDepartment) from request is not valid. The key value should be format of type 'Edm.Int32'

and inner exception as
 `Expected literal type token but found token getComapnyByDepartment`

Am i missing anything here or configuration issues.
I have gone through the MS [article](https://devblogs.microsoft.com/odata/attribute-routing-in-asp-net-core-odata-8-0-rc/) no luck here too

Sample code is [uploaded here][1]

Swagger error 
![image](https://github.com/OData/AspNetCoreOData/assets/39725883/578cc0a0-9bf7-44b9-bc32-4b4a830dc9ed)

  [1]: https://github.com/itsmegopi/OdataTrial

**Comment by habbes** [comment]
Hello @itsmegopi 

What version of OData were you on before the update?

I've looked at your sample code and it seems like you have disabled attribute routing: https://github.com/itsmegopi/OdataTrial/blob/main/Program.cs#L25 but you're using hardcoded route templates on some of your endpoints (here's [doc](https://learn.microsoft.com/en-us/odata/webapi-8/fundamentals/routing-overview?tabs=net60#attribute-routing) on attribute routing).

Consider enabling attribute routing if you want to custom route templates.

Also, based on your model, the path `WeatherForecast/GetRequest3` is not valid based on OData specification. In your model, you have defined `WeatherForecast` as an entity set of type `WeatherForecast`. According to OData Url conventions, if you have a path like `WeatherForecast/GetRequest3`, this will be interpreted as an entity set segment `WeatherForecast` followed by a key segment `GetRequest3`. But you `WeatherForecast` defines a integer ID property, and therefore `GetRequest3` is not a valid key for your entity because it's not an int. This is why the ODataUriParsers throws the exception that you see.

If you don't want to use OData URL rules for your endpoints, you should consider creating non-OData endpoints, i.e. endpoints not backed by an OData `IEdmModel`. You can still use ODataQueryOptions without on non-OData endpoints.

**Comment by xuzhg** [comment]
@itsmegopi 

Since you have correct `OData conventional routing` for `public IEnumerable<WeatherForecast> Get(int key)` (Controller Name is 'entityset name', the action name is 'Get', it only contains the 'key' parameter), so we built endpoints for this controller/action:


| Controller/Action|      HttpMethod      |  Template | IsODataConvention|
|----------|:-------------:|------:|---|
| DataRD....WeatherForecastController.Get (ODataRD) | GET | [api/v1/WeatherForecast({key})](https://localhost:7067/api/v1/WeatherForecast(%7Bkey%7D)) | YES  |
| DataRD....WeatherForecastController.Get (ODataRD) |   GET |   [api/v1/WeatherForecast/{key}](https://localhost:7067/api/v1/WeatherForecast/%7Bkey%7D) | YES |

Be noted, `api/v1/WeatherForecast/{key}` can match all. 

Meanwhile, you have a 'attribute routing' created at `Get3`

```C#
[HttpGet, Route("api/v1/WeatherForecast/GetRequest3")]
[EnableQuery]
public IQueryable<WeatherForecast> Get3(int forecastId, int temparature)
```

So, There is an endpoint built for `Get3()` controller/action

| Controller/Action|      HttpMethod      |  Template | IsODataRouting|
|----------|:-------------:|------:|---|
| ODataRD...WeatherForecastController.Get3 (ODataRD) | GET | [[api/v1/WeatherForecast/GetRequest3](https://localhost:7067/api/v1/WeatherForecast/GetRequest3)| NO|

Therefore, you have the following endpoints (in the following order), and **'Order' DOES matter**.

- [x]  api/v1/WeatherForecast({key})
- [x]  api/v1/WeatherForecast/{key}
- [x]  api/v1/WeatherForecast/GetRequest3

Since the 2nd match-all endpoint goes before 3rd endpoint, your request 'https://localhost:7067/api/WeatherForecast/GetRequest3` should always match the 2nd endpoint. 

Workaround:
1) Move `Get3` before `Get(int key)`. It should work, but it seems our KeySegmentTemplate throws expcetion. It seems now it 's  a problem. In the TryMatch(), we should log the error message and return false.

2) Change `Get()` routing template.

**Comment by itsmegopi** [comment]
> Hello @itsmegopi
> 
> What version of OData were you on before the update?
> 
> I've looked at your sample code and it seems like you have disabled attribute routing: https://github.com/itsmegopi/OdataTrial/blob/main/Program.cs#L25 but you're using hardcoded route templates on some of your endpoints (here's [doc](https://learn.microsoft.com/en-us/odata/webapi-8/fundamentals/routing-overview?tabs=net60#attribute-routing) on attribute routing).
> 
> Consider enabling attribute routing if you want to custom route templates.
> 
> Also, based on your model, the path `WeatherForecast/GetRequest3` is not valid based on OData specification. In your model, you have defined `WeatherForecast` as an entity set of type `WeatherForecast`. According to OData Url conventions, if you have a path like `WeatherForecast/GetRequest3`, this will be interpreted as an entity set segment `WeatherForecast` followed by a key segment `GetRequest3`. But you `WeatherForecast` defines a integer ID property, and therefore `GetRequest3` is not a valid key for your entity because it's not an int. This is why the ODataUriParsers throws the exception that you see.
> 
> If you don't want to use OData URL rules for your endpoints, you should consider creating non-OData endpoints, i.e. endpoints not backed by an OData `IEdmModel`. You can still use ODataQueryOptions without on non-OData endpoints.

We have migrated from OData from 7.1.0 to latest 8.2.3 also we updated our .NET Core framework from 2.2 to 8.0 using update assistant.

**Comment by itsmegopi** [comment]
> @itsmegopi
> 
> Since you have correct `OData conventional routing` for `public IEnumerable<WeatherForecast> Get(int key)` (Controller Name is 'entityset name', the action name is 'Get', it only contains the 'key' parameter), so we built endpoints for this controller/action:
> Controller/Action 	HttpMethod 	Template 	IsODataConvention
> DataRD....WeatherForecastController.Get (ODataRD) 	GET 	[api/v1/WeatherForecast({key})](https://localhost:7067/api/v1/WeatherForecast(%7Bkey%7D)) 	YES
> DataRD....WeatherForecastController.Get (ODataRD) 	GET 	[api/v1/WeatherForecast/{key}](https://localhost:7067/api/v1/WeatherForecast/%7Bkey%7D) 	YES
> 
> Be noted, `api/v1/WeatherForecast/{key}` can match all.
> 
> Meanwhile, you have a 'attribute routing' created at `Get3`
> 
> ```cs
> [HttpGet, Route("api/v1/WeatherForecast/GetRequest3")]
> [EnableQuery]
> public IQueryable<WeatherForecast> Get3(int forecastId, int temparature)
> ```
> 
> So, There is an endpoint built for `Get3()` controller/action
> Controller/Action 	HttpMethod 	Template 	IsODataRouting
> ODataRD...WeatherForecastController.Get3 (ODataRD) 	GET 	[[api/v1/WeatherForecast/GetRequest3](https://localhost:7067/api/v1/WeatherForecast/GetRequest3) 	NO
> 
> Therefore, you have the following endpoints (in the following order), and **'Order' DOES matter**.
> 
>     * [x]   api/v1/WeatherForecast({key})
> 
>     * [x]   api/v1/WeatherForecast/{key}
> 
>     * [x]   api/v1/WeatherForecast/GetRequest3
> 
> 
> Since the 2nd match-all endpoint goes before 3rd endpoint, your request '[https://localhost:7067/api/WeatherForecast/GetRequest3`](https://localhost:7067/api/WeatherForecast/GetRequest3%60) should always match the 2nd endpoint.
> 
> Workaround:
> 
>     1. Move `Get3` before `Get(int key)`. It should work, but it seems our KeySegmentTemplate throws expcetion. It seems now it 's  a problem. In the TryMatch(), we should log the error message and return false.
> 
>     2. Change HttpGet routing template at `Get3()` .

We will try after PR completion 

Confused about workaround point 2 , We have added a trial solution you can add comment over [there](https://github.com/itsmegopi/OdataTrial/blob/main/Controllers/WeatherForecastController.cs)
