### ISSUE TITLE
There seems to be an issue with case conversion when using Newtonsoft, I don't know yet if it's just case

### ISSUE THREAD

**Issue by Gaven-F** [OData/AspNetCoreOData#1209]
**Assemblies affected**
ASP.NET Core OData 8.2.5

**Describe the bug**
When using OData.Newtonsoft, the part(?) of Newtonsoft the rules do not work.

**Reproduce steps**
Let me show the code directly. It seems to be a small problem.
![image](https://github.com/OData/AspNetCoreOData/assets/133743603/0a8cbada-00b7-412a-a22e-a833b839b6b6)

**Data Model**
![image](https://github.com/OData/AspNetCoreOData/assets/133743603/317e5d90-ab8f-4a06-aaf7-131cc386fa2a)

**Request/Response**
![image](https://github.com/OData/AspNetCoreOData/assets/133743603/39ac23a0-c714-4adc-8bd9-e372335d57c9)
![image](https://github.com/OData/AspNetCoreOData/assets/133743603/e711fd9c-18f5-46ff-a83f-4d5be53aae9e)

Please pay attention to case!

**Expected behavior**
```
[
    {
        "name": "Bread"
    }
]
```

**Comment by julealgon** [comment]
@Gaven-F can you try adding the following setting to your NewtonsoftJson config?

```csharp
.AddNewtonsoftJson(option =>
{
    ...
    
    ((DefaultContractResolver)option.SerializerSettings.ContractResolver).NamingStrategy.ProcessDictionaryKeys = true;
})
```

Does this change the results for the `$select` call?

**Comment by Gaven-F** [comment]
OK, it works, but why?
Where can I go to find relevant information?

**Comment by julealgon** [comment]
> OK, it works, but why?

It's unfortunately a little bit obscure why this works... the reason is that when you use the `$select` operator, the underlying implementation relies on a model class that uses a `Dictionary` to keep track of the selected properties (instead of using the entity object itself). Since that uses a dictionary, you have to change dictionary-related rules for it to affect `$select` results.

Personally, I'm not a big fan of the approach that has been taken here (on the OData implementation side) but this has been mentioned in other issues already.

One thing to keep in mind, of course, is that that configuration you added affects _all_ dictionary objects in your payloads. To have it impact _only_ the `$select` (and `$expand`) operators would probably be doable but require quite a bit more effort using a custom converter on top of the `SelectExpandWrapper` object.

> Where can I go to find relevant information?

I'm sorry... I don't think this is actually mentioned anywhere 😅 I learned about the underlying structure of the select/expand model by looking at the code base and experimenting with it throughout the years.

But if you are talking about the Newtonsoft side, that is well documented on their end:
- https://www.newtonsoft.com/json/help/html/Properties_T_Newtonsoft_Json_Serialization_NamingStrategy.htm

And some relevant discussions on how to apply it here:
- [How to make Json Serialize ignore dictionary keys](https://stackoverflow.com/questions/58501943/how-to-make-json-serialize-ignore-dictionary-keys)

**Comment by corranrogue9** [comment]
@Gaven-F our established practice for this can be found in the documentation [here](https://github.com/OData/AspNetCoreOData/blob/main/docs/camel_case_scenarios.md). It sounds like you already got what you need from @julealgon  though. I'm going to resolve now.

**Comment by Gaven-F** [comment]
But now I seem to have discovered a similar new problem.

 When I access the route of /odata/test..., the data obtained is still in big camel case (the first letter is capitalized), and through the above operation:

> @Gaven-F our established practice for this can be found in the documentation [here](https://github.com/OData/AspNetCoreOData/blob/main/docs/camel_case_scenarios.md). It sounds like you already got what you need from @julealgon though. I'm going to resolve now.

I can get the data I want normally in other routes

This is my configuration:
![image](https://github.com/OData/AspNetCoreOData/assets/133743603/67c9bc24-ecff-4677-818c-308cbf41aec2)

Once I use the interface under the routing component, it becomes disobedient (will not be serialized correctly)

*另外，路由组件似乎还有[其他的问题](https://github.com/OData/AspNetCoreOData/issues/1218#issue-2249716949)*
