### ISSUE TITLE
The property cannot be used in the $orderby query option.

### ISSUE THREAD

**Issue by daningalla** [OData/AspNetCoreOData#124]
Bare bones setup on a single entity context:

```
services.AddOData(opt =>
{
    var builder = new ODataConventionModelBuilder();
    builder.EntitySet<Tenants>("tenants").EntityType.HasKey(t => t.Id);
    opt.AddModel(builder.GetEdmModel()).Count().Filter().Expand().Select().OrderBy().SetMaxTop(25);
});
```

I cannot $filter on any field, $orderby on an field, etc., service returns 400 with:

```
{
    "Message": "The query specified in the URI is not valid. The property 'Id' cannot be used in the $orderby query option.",
    "ExceptionMessage": "The property 'Id' cannot be used in the $orderby query option.",
    "ExceptionType": "Microsoft.OData.ODataException",
    "StackTrace": "   at Microsoft.AspNetCore.OData.Query.Validator.OrderByModelLimitationsValidator.TryValidate(OrderByClause orderByClause, Boolean explicitPropertiesDefined)\r\n   at Microsoft.AspNetCore.OData.Query.Validator.OrderByQueryValidator.Validate(OrderByQueryOption orderByOption, ODataValidationSettings validationSettings)\r\n   at Microsoft.AspNetCore.OData.Query.OrderByQueryOption.Validate(ODataValidationSettings validationSettings)\r\n   at Microsoft.AspNetCore.OData.Query.Validator.ODataQueryValidator.Validate(ODataQueryOptions options, ODataValidationSettings validationSettings)\r\n   at Microsoft.AspNetCore.OData.Query.ODataQueryOptions.Validate(ODataValidationSettings validationSettings)\r\n   at Microsoft.AspNetCore.OData.Query.EnableQueryAttribute.ValidateQuery(HttpRequest request, ODataQueryOptions queryOptions)\r\n   at Microsoft.AspNetCore.OData.Query.EnableQueryAttribute.OnActionExecuting(ActionExecutingContext actionExecutingContext)"
}
```

Similar error for $filter. I know I'm missing something very simple.

**Comment by xuzhg** [comment]
@daningalla Can you share me your repro?

**Comment by daningalla** [comment]
https://github.com/daningalla/ODataBug

**Comment by xuzhg** [comment]
@daningalla Thanks for sharing your repo. I am sorry my response is later. 

1) your controller has "[Route("api/[controller]")]",  So, "GetTenants()" has a api routing.

2) Your sample don't have `builder.EntitySet<Tenants>("tenants").EntityType.HasKey(t => t.Id);` this line code. But I assume you forgot to add it. If I add it, there's no OData routing. because case is sensitive. If you change "tenants" as "Tenants", then OData will build the OData routing for "GetTenants()", because now, it meets the convention rules.

3) Any way, let's keep "tenants", so there's only one route. the route template is "api/tenants".

4) `http://localhost:5000/api/tenants?$orderby=Id` can't work in RC because there's an issue. That's fixed after RC. If you use the latest nightly, it should work fine.  Please find the nightly feed from https://github.com/OData/AspNetCoreOData/blob/master/README.md

**Comment by KenitoInc** [comment]
@daningalla Seems the issue was fixed. If it still exists, re-open this issue or open a new issue
