### ISSUE TITLE
OData filtering doesn't work with polymorphic entities

### ISSUE THREAD

**Issue by axserfezi** [OData/AspNetCoreOData#1291]
Hello,
I am trying to enable OData filtering in my existing rest api application but I have problem with polymorphic entities.
I can't apply any query parameter that has something to do with data filtering over inherited objects.
Problem is known for a while, I consulted already https://github.com/OData/AspNetCoreOData/issues/469 and tried to filter with fully qualified entity name and that is working but doesn't looks good in case of external client implementation.

Is there any solutions for this problem?

In attachment provided small test application with stack trace of an error when I try to search for Id from underlying table:
https://localhost:7255/odata/Tickets?$filter=BarcodeId%20eq%20%27123456%27

Tools:
.NET 8, 
Microsoft.AspNetCore.OData 8.2.5,
Microsoft.EntityFrameworkCore 8.0.7,
Npgsql.EntityFrameworkCore.PostgreSQL 8.0.4.

Thank you!
BR
 
[Stack_trace.txt](https://github.com/user-attachments/files/16454437/Stack_trace.txt)
[Test_OData_Polymorph.zip](https://github.com/user-attachments/files/16454360/Test_OData_Polymorph.zip)

**Comment by xuzhg** [comment]
In order to access a property of the derived type, you should add a cast segment to either the $filter:

### 1 get the tickets if its type is BarcodeEntity and BarcodeId is 123456.
GET  https://localhost/odata/Tickets?$filter=NamespaceName.BarcodeEntity/BarcodeId eq '123456'

### 2 Or to the resource path:

 get the tickets, cast to the BarcodeEntity subtype
GET  https://localhost/odata/Tickets/NamespaceName.BarcodeEntity?$filter=BarcodeId  eq '123456'


To make the second working, you should have corresponding endpoint created in the controller.

Maybe similar to 'https://github.com/OData/WebApi/issues/2850'.  It could be working when customer is using ASP.NET OData (.NET Framework) 7.x . But, that's not compatible to OData spec.

**Comment by axserfezi** [comment]
Thank you for help!

**Comment by WanjohiSammy** [comment]
@axserfezi 

This behavior is intentional in Microsoft.AspNetCore.OData 8.x. The team observed this behavior in version 7.x and chose to acknowledge it without making changes but decided not to carry it forward to version 8.x and beyond. This behavior is not strictly spec-compliant and leads to inconsistencies in customer experience.
