### ISSUE TITLE
Unable to define define custom resource prefix

### ISSUE THREAD

**Issue by fykou** [OData/AspNetCoreOData#1366]
**Assemblies affected**
ASP.NET Core OData 8.x
*Microsoft.AspNetCore.Odata 8.2.4 to be spesific* 

**Describe the bug**
I seem unable to register my endpoint as an odata endpoint using attribute routing with a nested/grouped resource path.
Due to the structure of existing endpoints the path has to be `api/v{version:apiVersion}/[SomeService]/[Entity]`, however, Odata does not seem to understand the [SomeService] segment. I've tried a lot of things, and the closest I've come is by including `SomeService` in the `AddRouteComponents` prefix, however, this messes up my `$metadata` andI have multiple Odata controllers that has this requirement.
> It kind of seemed like the `[EnableNestedPaths]` from the webapi docs would be relevant, but from what I read, this is not available in Odata8.

**Controller**
```c#
[ApiController]
[ApiVersion(1.0)]
[Route("api/v{version:apiVersion}/SomeFeature")]
public class SomeFeatureController(ISomeFeatureService someFeatureService) : ODataController
{

    [HttpGet("SomeEntity")]
    public async Task<IActionResult> GetSomeData(ODataQueryOptions<SomeModel> options)
    {
        var response = await someFeatureService.GetSomeModel(options);
        return Ok(response);
    }

    [HttpGet("SomeOtherEntity")]
    public async Task<IActionResult> GetSomeOtherData(ODataQueryOptions<SomeOtherModel> options)
    {
        var response = await someFeatureService.GetSomeOtherModel(options);
        return Ok(response);
    }
}
```

**EDM (CSDL) Model**
```c#
builder.EntitySet<SomeModel>("SomeEntity").EntityType.HasKey(x => x.Id)
builder.EntitySet<SomeOtherModel>("SomeOtherEntity").EntityType.HasKey(x => x.Id)
```

**Program.cs**
```c#
options.AddRouteComponents("api/v{version:apiVersion}", EdmModel);
```

**Expected behavior**
I would expect some configuration or detection to be available for odata to detect my route.

**Additional context**
 `Microsoft.AspNetCore.OData.Routing.Conventions.AttributeRoutingConvention[0] The path template 'api/v{version:apiVersion}/SomeFeature/SomeEntity' on the action 'GetSomeData' in controller 'SomeFeature' is not a valid OData path template. Resource not found for the segment 'SomeFeature'.`

**Comment by julealgon** [comment]
@fykou I'm not sure what you are trying to do is _possible_... you are basically trying to introduce an extra segment that doesn't map to anything at the EDM level, which is basically just not OData compliant, unless you made `SomeFeature` a singleton resource that has child `SomeEntity` instances.

I've done something like that in a multi-tenant API before but I'm not sure that's what you really want to do here.

> It kind of seemed like the `[EnableNestedPaths]` from the webapi docs would be relevant, but from what I read, this is not available in Odata8.

I believe you misunderstood what `[EnableNestedPaths]` does in the non-Core version of OData. That attribute just allows you to call nested _properties or navigations_ on an entity and have the controllers handle it automatically for you instead of forcing you to create dedicated routes for each of those navigations/properties.

Since your "service" `SomeFeature` segment is not really an entity at all, that doesn't apply there.

**Comment by fykou** [comment]
Ah, I see. I'm guessing in the end I'll have to restructure the resource paths and introduce a new version then. Thanks for your time.
