### ISSUE TITLE
Add EnableCaseInsensitive to ODataOptions

### ISSUE THREAD

**Issue by dsidedp** [OData/AspNetCoreOData#255]
For Json controllers the only way to enable case insensitivity for UriResolver is to use reflection and change settings in private ODataUriResolver.Default. 

Could you please expose EnableCaseInsensitive via ODataOptions, in the save way you did with EnableNoDollarQueryOptions.

**Comment by josundt** [comment]
Second that, +1 vote.

After migrating Microsoft.AspNetCore.OData 7.x -> 8.x in one of our products, I found that default parsing of model **property paths** in queries (Uri) now are _case sensitive_, while they were _case insensitive_ in 7.x. 

I am not sure if this was intentional - I did not find any information about this change in your change/release logs.
Maybe default should be the same as in 7.x (case insensitive).


@dsidedp Can you please share the code used for on your temporary workaround using reflection with ODataUrlResolver.Default

**Comment by josundt** [comment]
Thanks @dsidedp - that did the trick 👍
This setting should definitely be configurable in `ODataOptions`, and I suggest having `true` as default value to eliminate the breaking change between 7.x and 8.x

**Comment by xuzhg** [comment]
@josundt @dsidedp 
Sorry for later response.
For request Uri case sensitive, it's enabled by default.
For the payload case sensitive, it's enabled in latest version. So far, it works fine for primitive-type property.

**Comment by dsidedp** [comment]
The original issue is for version 8.0.1.  Sorry, forget to mention this in the first post.

As for now, there is a new version of Microsoft.OData.Core (7.9.1) where the Default ODataUriResolver is actually created, but it still created using [default constructor](https://github.com/OData/odata.net/blob/4e263ca4b94d01f2d105d8282c62ec272cfcd1bb/src/Microsoft.OData.Core/UriParser/Resolver/ODataUriResolver.cs#L26), so EnableCaseInsensitive will still be false.

So, queries like `$filter=productstatus ne 'Dropped' ` will fail, while `$filter=ProductStatus ne 'Dropped'` works fine.

Do I miss something?

**Comment by xuzhg** [comment]
see a fixed at: 4ab80c7caa657dcadef2815cbdf423402829a67b

**Comment by KenitoInc** [comment]
Issue was resolved. Closing this
