### ISSUE TITLE
OData completely ignores camelCase

### ISSUE THREAD

**Issue by JensMagnus** [OData/AspNetCoreOData#270]
Neither 

```
services.AddControllers()
                .AddJsonOptions(options => options.JsonSerializerOptions.PropertyNamingPolicy = JsonNamingPolicy.CamelCase)
                .AddOData(opt => opt.AddRouteComponents("", GetEdmModel())
                   .Select()
                   .OrderBy()
                   .Expand()
                   .Filter()
                   .SetMaxTop(10000)
                   .SkipToken()
                   .Count())

```
Nor 

```
var builder = new ODataConventionModelBuilder();

            builder.EnableLowerCamelCase();
```

Works.

All my properties are named 

```
[
 {
 "Id": 1,
"Name": "Test"
}
]
```

What's going on? Anyone got a fix for this? Underlying source is PostgreSQL through EntityFrameworkCore, which I might suspect for being the fulcrum. 

```
private static IEdmModel GetEdmModel()
        {
            var builder = new ODataConventionModelBuilder();

            builder.EnableLowerCamelCase();

            builder.EntitySet<Entity1>("entity1");
            builder.EntitySet<Entity2>("entity2");

            return builder.GetEdmModel();
        }

```

I am using the latest version of OData and the latest preview of .NET 6 (preview 6)

**Comment by JensMagnus** [comment]
Hi Habbes, thanks for your reply. I can PM you the actual URL if you're interested. 

`[{"Room":{"Name":"Office"},"Id":"0a362b0d-cdfc-4603-b844-3abc0c0eb25e","Temperature":32.2,"Created":"2021-06-17T15:56:44.346953"}]`

This is the raw JSON response from the API.

`https://<REDACTED>temperature-messurement?$select=Id,Temperature,Created&top=1&orderby=Temperature%20desc&$expand=Room($select=Name)`

The controller in question:

```
[Route("temperature-messurement")]
    public class TemperatureMessurementController : ControllerBase
    {
        private readonly DatabaseContext databaseContext;

        public TemperatureMessurementController(DatabaseContext databaseContext)
        {
            this.databaseContext = databaseContext;
        }

        [HttpGet]
        [EnableQuery]
        public IActionResult Get()
        {
            return Ok(databaseContext.TemperatureMeassurements);
        }
    }
```


```
private static IEdmModel GetEdmModel()
        {
            var builder = new ODataConventionModelBuilder();

            builder.EnableLowerCamelCase();

            builder.EntitySet<TemperatureMeassurement>("temperature-messurement");

            return builder.GetEdmModel();
        }
```

**Comment by habbes** [comment]
@JensMagnus you're route isn't being recognized as an OData route. An easy way to confirm this is to use the OData route debugging page. You can enable this by adding `app.UseODataRouteDebug()` in the `Configure()` method of your `Startup` class. Then you access the page by visiting the `/$odata` endpoint. This will display a table of all the OData routes and their controller actions, followed by a table of the non-OData routes. Find out which table the `GET temperature-messurement` route is listed in, it's probably listed in the non-OData section.

I've been able to reproduce this issue and found that the culprit is the use of the `[Route("temperature-messurement")]` attribute on the controller. Apparently this makes it a non-OData route. I'm not sure if this is a bug or expected, @xuzhg could advise. But to fix, simply add the `[ODataAttributeRouting]` to the controller as well, this tells OData that your controller is using attribute routing. It comes from the `Microsoft.AspNetCore.OData.Routing.Attributes` namespace.

So your controller code would now look like this:

```c#
/* other using statements */
using Microsoft.AspNetCore.OData.Routing.Attributes;

namespace YourNameSpace.Controllers
{
    [ODataAttributeRouting]
    [Route("temperature-messurement")]
    public class TemperatureMessurementController : ControllerBase
    {
        private readonly DatabaseContext databaseContext;

        public TemperatureMessurementController(DatabaseContext databaseContext)
        {
            this.databaseContext = databaseContext;
        }

        [HttpGet]
        [EnableQuery]
        public IActionResult Get()
        {
            return Ok(databaseContext.TemperatureMeassurements);
        }
    }
}
```

Let me know if this works.

**Comment by JensMagnus** [comment]
@habbes Thank you so much.

That resolved the issue with camelCase! I can see that the response now has a "value" property which encapsulates the actual response.

`https://localhost:44327/temperature-messurement?$select=Id,Temperature,Created&top=1&orderby=Temperature%20desc&$expand=Room($select=Name)&$top=1`

```
{
"@odata.context": "https://localhost:44327/$metadata#temperature-messurement(id,temperature,created,room(name))",
"value": [
{
"id": "00000505-f1bc-4ce6-ada3-36f4518a0136",
"created": "2021-04-16T17:03:33.526389+02:00",
"temperature": 26.6,
"room": {
"name": "Bedroom"
}
}
]
}
```

**Comment by habbes** [comment]
Glad to hear it worked @JensMagnus. Out of curiosity, did you intend to name your entity `TemperatureMessurement` or was it a typo (instead of `TemperatureMeasurement`):
