### ISSUE TITLE
Versioning with AddRouteComponents not fully working?

### ISSUE THREAD

**Issue by jhermsen** [OData/AspNetCoreOData#327]
I was trying to use the AddRouteComponents to add versioning, but there is some strange behaviour going on.
Maybe I just missed something. I started with reading the blogs written by @xuzhg. 

What I did was create the standard API project with current .Net 6 (6.0.100-rc.1.21463.6).
Then altered the structure to add the versioned controllers and models:
```
WebApplication(Project)
  Controllers
    v1
      WeatherForecastController (class)
    v2
      WeatherForecastController (class)
  Models
    v1
      EdmModelBuilder (class)
      WeatherForecast (class)
    v2
      EdmModelBuilder (class)
      WeatherForecast (class) < Added extra field with dummy data
  Program (class)
```

Then added the following to my program:
```builder.Services
    .AddControllers()
    .AddOData(options => options
        .Select()
        .Filter()
        .Expand()
        .SetMaxTop(100)
        .Count()
        .OrderBy()
        .AddRouteComponents("v1", WebApplication1.Models.v1.EdmModelBuilder.GetEdmModel())
        .AddRouteComponents("v2", WebApplication1.Models.v2.EdmModelBuilder.GetEdmModel())
    );
```

The controllers I changed by adding [EnableQuery] on Get methods.
Also changed the base class to ODataController.
Then I was struggling with the routing.
v1 WeatherForecastControler:
```
    [Route("/v1/[controller]")]
    [ODataRouteComponent("v1")]
    public class WeatherForecastController : ODataController
```

v2 WeatherForecastController:
```
    [Route("/v2/[controller]")]
    [ODataRouteComponent("v2")]
    public class WeatherForecastController : ODataController
```

Using this setup the /v1/WeatherForecast gave the error: "AmbiguousMatchException: The request matched multiple endpoints. Matches:". /v2/WeatherForecast gives the same error. And v1/WeatherForecast/$count and v2/WeatherForecast/$count do work.

I disabled the RouteAttribute on the v1 controller and /v1/WeatherForecast starts working, but v2 still says AmbiguousMatchException. Why is that or better said what am I doing wrong here?

Also included the test project.
[WebODataTest.zip](https://github.com/OData/AspNetCoreOData/files/7295351/WebODataTest.zip)

**Comment by xuzhg** [comment]
@jhermsen Your "WeatherForecastController" and "Get()" method meet the conventional routing.

So, conventional routing will build the following two endpoints for  v1.WeatherForecastController.Get:

1)  /v1/weatherforecast
2)  /v1/weatherforecast/$count

So, conventional routing will build the following two endpoints for  v2.WeatherForecastController.Get:

1)  /v2/weatherforecast
2)  /v2/weatherforecast/$count

However, OData attribute routing is also enabled by default. OData attribute routing uses:
[RouteAttribute], [HttpGet] to do the routing.
If the combined route template from [RouteAttribute] and [HttpGetAttribute] meets the OData routing. a new endpoint will create to that action.
Since the placeholdertoken (aka, [controller]) is not fully supported. So, it's not be considered as OData attribute routing.
And it will go to the normal ASP.NET Core routing.

Based on this, each Get() method has:

1)  /v1/weatherforecast          --> from OData conventional routing
2)  /v1/weatherforecast/$count   --> from OData conventional routing
3) /v1/weatherforecast   ---> from ASP.NET Core attribute routing

It's duplicated.  Just remove [Route....] on the controller can make it working.
