### ISSUE TITLE
Enum as function parameter is not bound correctly

### ISSUE THREAD

**Issue by krnrpl** [OData/AspNetCoreOData#404]
I have a function parameter which is an enum type. When I call the function, the value of my parameter is wrong, it is always the default enum value (first one).
```
public enum Mode
{
	Export,
	Import
}
public virtual IActionResult GetDistinct(ODataQueryOptions<Model> options, Mode mode)
{
	// mode is always Mode.Export
}
```
I call it like this: `/api/Model/GetDistinct(mode='Import')`

Checking the OData path (`options.Context.Path`) I find a `OperationSegmentParameter` with matching parameter name and value `1` (matching `Mode.Import`). So I guess the URI is parsed correctly, but then it fails somewhere.
Other parameters (e.g. strings, which I left for clarity) are bound correctly.

**Comment by xuzhg** [comment]
@krnrpl can you add [FromODataUri] to Model mode parameter and see whether it's ok or not?

**Comment by krnrpl** [comment]
@xuzhg thanks for the quick response, that does indeed solve it. Is there any advice when to use this attribute?

**Comment by xuzhg** [comment]
typically, if the data value in the request can't bind to the parameter in action using default model binding, you'd better to use this attribute. For example:  Enum type, string (since string value in OData is single quoted, but now we don't need this attribute for string), entity or complex value in request path, etc.
