### ISSUE TITLE
Expand created entity

### ISSUE THREAD

**Issue by Robelind** [OData/AspNetCoreOData#407]
```
class A
{
  public int Id {get; set;}
  public B B {get; set;}
}

class B
{
  public int Id {get; set;}
  public string Value {get; set;}
}

[HttpPost]
public IActionResult Post([FromBody] A a)
{
    A created = .......... // Create A entity with linked B entity.
    return(Created(created));
}
```
In this scenario I'd want the returned A-entity to have its B-property expanded.
How to achieve this?

**Comment by xuzhg** [comment]
@Robelind 
I try to understand your requirement. So, You are using "Post" to create a new 'A' and bind it to 'a' instance. 

So, what's "created"? why don't you use 'a' directly? because 'a' holds the value from "Post" request body.

And in the request body, you can add "B" property when you create new A.

**Comment by Robelind** [comment]
"created" is the A-object that has been persisted to the database, bound to a B-instance.
"a" does not have a complete B-object since its B-property is populated by odata.bind and thus only have its Id-property set.

In the above scenario both A and B and registered as entity-types in the EDM:
```
builder.EntitySet<A>("TestAs");
builder.EntitySet<B>("TestBs");
```
and the response is:
```
{
    "@odata.context": "http://localhost:53205/api/$metadata#TestAs/$entity",
    "Id": 1
}
```
If you instead **not** register B as an entity-type and remove its "Id"-property:
```
//builder.EntitySet<B>("TestBs");
public class B
{
    //public int Id { get; set; }
    public string Value { get; set; }
}
```
the response is:
```
{
    "@odata.context": "http://localhost:53205/api/$metadata#TestAs/$entity",
    "Id": 1,
    "B": {
        "Value": "Test"
    }
}
```
This can of course not be used, since B must be a proper entity type.

**Comment by xuzhg** [comment]
@Robelind I see.
1) If you remove `builder.EntitySet<B>("TestBs")` and the Id property from class B, the model builder will build the `B` type as `Complex Type`, and the property `B` on class `A` is complex property. The complex property is serialized with the entity. So, that's why you have B property in the response.

2) If you don't remove the codes, `B` is entity type and the property `B` is navigation property. To get navigation property, you should use a) $expand=B b) or auto-expand feature.

**Comment by marabooy** [comment]
@Robelind Could you also share the post request data. To perform the expand during creation you could add the query option to the url of the request and enable query attribute to the method.
`url/TestAs?$expand=b` and `[EnableQuery]` on the method.

**Comment by Robelind** [comment]
Request body is:
```
{
    B@odata.bind: "https://localhost:44383/api/TestBs(1)"
}
```
Adding `[EnableQuery]` and changing the query string for the POST to `http://localhost:53205/api/TestAs?$expand=B` makes no difference.

**Comment by julealgon** [comment]
@Robelind , could you please try changing your action code to this, and seeing if the expansion works?
```csharp
[HttpPost]
[EnableQuery]
public SingleResult<A> Post([FromBody] A a)
{
    A created = .......... // Create A entity with linked B entity.
    return SingleResult.Create(new [] { created }.AsQueryable());
}
```

**Comment by Robelind** [comment]
@julealgon, this change makes the expansion work.
Thanks.

**Comment by julealgon** [comment]
I'm glad it worked for you @Robelind . I posted the comment because I was looking at a larger issue that I described here:
- https://github.com/OData/AspNetCoreOData/issues/434

As you could tell, the solution I posted is a bit convoluted, so it is less than ideal. I wasn't exactly sure that your problem was a subset of it, but it appears that's the case.

Once the main issue is fixed, it should be possible for you to move back to the simpler `Created` call (which provides other benefits as well, like automatically populating the `Location` header, as well as allowing client-side control of the payload presence via `Prefer` header.
