### ISSUE TITLE
OData 8.0.6/EF6/.NET 6 - Query params without '$' prefix do not work

### ISSUE THREAD

**Issue by jasonjoh** [OData/AspNetCoreOData#443]
I'm writing a simple OData-enabled API to test some client tooling against, and I'm running into an issue with standard query parameters (`$select`, `$top`, etc.). My API returns properly (only requested properties are included) with a request like:

```
GET /ToDoItems?$select=name,isComplete
```

But does not with a request like:

```
GET /ToDoItems?select=name,isComplete
```

Without the `$`, all properties are returned. Essentially the parameter is ignored. This is not limited to `$select`, I've also seen that `$top` is ignored without the `$`.

My Program.cs:

```csharp
using Microsoft.AspNetCore.OData;
using Microsoft.EntityFrameworkCore;
using Microsoft.Identity.Web;
using Microsoft.OData.ModelBuilder;
using ToDoApi.Models;

var builder = WebApplication.CreateBuilder(args);

// Add services to the container.

builder.Services
    .AddMicrosoftIdentityWebApiAuthentication(builder.Configuration);

builder.Services.AddControllers().AddOData((opt, services) =>
{
    opt.Select().Filter().SkipToken().OrderBy().SetMaxTop(100).Count();
    opt.TimeZone = TimeZoneInfo.Utc;

    var odataBuilder = new ODataConventionModelBuilder();
    odataBuilder.EnableLowerCamelCase();
    odataBuilder.EntitySet<ToDoItem>("ToDoItems");
    opt.AddRouteComponents(odataBuilder.GetEdmModel());
});

builder.Services.AddDbContext<ToDoContext>(opt =>
    opt.UseInMemoryDatabase("ToDoList"));

var app = builder.Build();

// Configure the HTTP request pipeline.
app.UseHttpsRedirection();

app.UseRouting();

app.UseODataRouteDebug();

app.UseAuthentication();
app.UseAuthorization();

app.MapControllers();

app.Run();
```

My ToDoItemsController.cs:

```csharp
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.OData.Deltas;
using Microsoft.AspNetCore.OData.Extensions;
using Microsoft.AspNetCore.OData.Query;
using Microsoft.AspNetCore.OData.Routing.Controllers;
using Microsoft.EntityFrameworkCore;
using Microsoft.Identity.Web.Resource;
using ToDoApi.Models;

namespace ToDoApi.Controllers
{
    [Authorize]
    [RequiredScope("ToDoItem.ReadWrite")]
    public class ToDoItemsController : ODataController
    {
        private readonly ToDoContext _context;
        private readonly ILogger<ToDoItemsController> _logger;

        public ToDoItemsController(ToDoContext context, ILogger<ToDoItemsController> logger)
        {
            _context = context;
            _logger = logger;
        }

        // GET: /ToDoItems
        [HttpGet]
        [EnableQuery()]
        public async Task<ActionResult<IQueryable<ToDoItem>>> GetToDoItems()
        {
            return _context.ToDoItems;
        }

        // GET: /ToDoItems/5
        [HttpGet]
        [EnableQuery()]
        public async Task<ActionResult<ToDoItem>> GetToDoItem(long key)
        {
            var todoItem = await _context.ToDoItems.FindAsync(key);

            if (todoItem == null)
            {
                return NotFound();
            }

            return todoItem;
        }        
    }
}
```

**Comment by yzorg** [comment]
This behavior is in the spec, and MS docs.  from https://docs.microsoft.com/en-us/odata/concepts/queryoptions-overview#system-query-options

> .. OData Protocol V4.01 based services support case-insensitive system query option names specified with or without the $ prefix.

**Comment by julealgon** [comment]
I can confirm it doesn't work even by manually setting `EnableNoDollarQueryOptions` during startup. It appears that the flag in `ODataOptions` is being ignored in favor of another flag with the same name in `Microsoft.OData.UriParser.EnableNoDollarQueryOptions`. Additionally, the default values across both properties is different: it is set to `true` on `ODataOptions`, but `false` in `UriParser`. This feels badly designed and very error prone.

Here is where the decision is being made apparently:
https://github.com/OData/AspNetCoreOData/blob/a4ada0f0038434caeda97b9524b4f770d461626e/src/Microsoft.AspNetCore.OData/Query/ODataQueryOptions.cs#L1096-L1114

And it appears that it will always fetch using the `UriParser` since that is registered in the beginning:
https://github.com/OData/AspNetCoreOData/blob/a4ada0f0038434caeda97b9524b4f770d461626e/src/Microsoft.AspNetCore.OData/ODataOptions.cs#L307

It's not clear to me why there are 2 places for configuring this setting. Ideally in my view, it should only come from the `ODataOptions`, which is exposed to the user for configuration and is already defaulted to `true`.

**Comment by xuzhg** [comment]
@julealgon @jasonjoh 
as a workaround:

```c#

builder.Services.AddControllers().AddOData((opt, services) =>
{
    opt.Select().Filter().SkipToken().OrderBy().SetMaxTop(100).Count();
    opt.TimeZone = TimeZoneInfo.Utc;

    var odataBuilder = new ODataConventionModelBuilder();
    odataBuilder.EnableLowerCamelCase();
    odataBuilder.EntitySet<ToDoItem>("ToDoItems");
    opt.AddRouteComponents("", odataBuilder.GetEdmModel(),
        s => s.AddSingleton<ODataUriResolver>(sp => new UnqualifiedODataUriResolver { EnableCaseInsensitive = true, EnableNoDollarQueryOptions = true }));
});
```

And it's a gap to put the EnableNoDollarQueryOptions  on ODataOptions to lower layer. 

Thanks.
