### ISSUE TITLE
DataMember("Name=XXX")] is ignored on key properties

### ISSUE THREAD

**Issue by richardu** [OData/AspNetCoreOData#448]
I have an EDM class with property `Token` as follows:

```
[DataContract(Name = "Node")]
public abstract class NodeEDM
{
    [Required]
    [DataMember(Name = "id")]
    public Guid Token { get; set; }

    ...
}
```

If this property is the key, set using the `[Key]` attribute or model builder as follows:

```
var builder = new ODataConventionModelBuilder();
builder.EntitySet<EDM.NodeBaseEDM>("Nodes")
    .EntityType
    .HasKey(x => x.Token);
```

...then serialization of the property ignores the `DataMember` name and the property is serialized using the C# property name, not the `DataMember` name. The output is as follows:

```
{
    "@odata.context": "...",
    "@odata.type": "...",
    "Token": "b3f6eb52-7cd9-473d-927f-00974d89beb6",
    ...
}
```

It works for all non-key properties.

Similarly, deserialization doesn't work if the `DataMember` name is used (e.g. in `CREATE` or `UPDATE`); an exception is thrown because no matching property is found on the model.

Is this a bug or by design for some reason?

**Comment by julealgon** [comment]
While reading and testing your question, I was surprised that `[DataContract]` even worked in the first place, since it doesn't work with `System.Text.Json` itself:
- https://github.com/dotnet/runtime/issues/29975

I thought OData leveraged whatever Json serializer was configured in the project but that doesn't seem to be the case necessarily oO.

Having said that, can you remove the `.HasKey(x => x.Token);` bit in your case? Since you are using "id" as the name, that would match the convention without it having to be explicitly specified. It appears to work fine that way at least from my testing.

Also, the problem you describe is not limited to keys: using a manual `Property(e => e.SomeProperty)` to map a property on the EDM will _also_ ignore the `DataMember` attribute and use the value from the property name itself. This _seems_ to be by design, as it is probably taking the name from the expression you pass... I'd assume that, if one wanted to customize this, one would have to add the property using a more low level approach where you can specify things by string maybe?

As for the payload not matching on create/update, I can't reproduce that one. If I add a `[DataMember(Name = "Whatever")]` to a property and try to POST a new entry using that, it works fine for me (again, surprisingly enough lol):

```csharp
    [DataContract]
    public class WeatherForecast
    {
        [DataMember(Name = "id")]
        public int Whatever { get; set; }

        public Microsoft.OData.Edm.Date Date { get; set; }

        [DataMember(Name = "Whatever2")]
        public int TemperatureC { get; set; }

        public int TemperatureF => 32 + (int)(TemperatureC / 0.5556);

        public string? Summary { get; set; }
    }
```

`POST http://localhost:5151/WeatherForecasts`
Body:
```json
{
    "Whatever2": 100
}
```
Response:
```json
{
    "@odata.context": "http://localhost:5151/$metadata#WeatherForecasts/$entity",
    "id": 51,
    "Whatever2": 100
}
```

**Comment by xuzhg** [comment]
@richardu I think @julealgon's comments make sense. And allow me to add a little bit.

OData model builder supports "conventional model builder" and "non-conventional model builder". 

* conventional model builder: build the model using a set of conventions or attributes
* non-conventional model builder: build the model calling a set of fluent APIs.

Non-conventional has higher priority than conventional. It means any types or properties are defined using fluent APIs, model builder will suppress applying the conventional rules.

Since "HasKey(...)" is a fluent API, you defined the property by yourself, the rules of the convention are suppressed.

You can take the suggestion from @julealgon to make it work or call 'Name" after "HasKey(..) to change the name.

**Comment by richardu** [comment]
Hi @julealgon,

It's hard to find docs relating to DataContract / DataMember, but it is discussed here: https://docs.microsoft.com/en-us/odata/webapi/convention-model-builder.

OData seems to be a law unto itself - annoyingly, it's got its own serializer, so it doesn't just use whatever is configured already (I'd already replaced System.Text.Json with Newtonsoft.Json in my API before adding OData) but it doesn't use it. As an aside, Newtonsoft serializes 'dynamic' (i.e. object) correctly but OData just throws an exception. Unhelpful!)

I've removed Token and replaced it with id as you suggest - as follows to retain consistency with the rest of the API internally:

```
[IgnoreDataMember]
public Guid Token { get; set; }

[Required]
[DataMember]
public Guid id
{
    get { return this.Token; }
    set { this.Token = value; }
}
```

My only minor gripe is that it generates an `IDE10006: Naming rule violation` because it doesn't start with an uppercase letter.

RE: renaming properties on POST: again, it only complained about the key property. Renaming other properties worked fine.

@xuzhg: thx for the info on priorities. I guess i should stick to using one or the other!

Now to try to get it play nicely with Swagger...!

Cheers,
Rich

**Comment by julealgon** [comment]
> My only minor gripe is that it generates an IDE10006: Naming rule violation because it doesn't start with an uppercase letter.

@richardu IIRC there is an option to serialize in camelCase, is there not?

Can you try calling `EnableLowerCamelCase` on the EDM builder like this?

![image](https://user-images.githubusercontent.com/461579/150367669-ce4c02ca-6661-44a3-b3bf-6cec23c8561d.png)

You'd then use a normal PascalCase property there and avoid the warning.

**Comment by julealgon** [comment]
Also

> It's hard to find docs relating to DataContract / DataMember, but it is discussed here: https://docs.microsoft.com/en-us/odata/webapi/convention-model-builder.
>
> OData seems to be a law unto itself - annoyingly, it's got its own serializer, so it doesn't just use whatever is configured already (I'd already replaced System.Text.Json with Newtonsoft.Json in my API before adding OData) but it doesn't use it. As an aside, Newtonsoft serializes 'dynamic' (i.e. object) correctly but OData just throws an exception. Unhelpful! I ended up creating a class derived from ODataEdmTypeSerializer which just calls Newtonsoft.Json.)

This seems all really bad to me... @xuzhg , are there plans to get rid of custom Json serialization and leverage the library currently configured on MVC instead? Is there a strong reason today for not doing so?

Being able to use the same serializer would be a step further into making OData much easier to use and less "magical"/more reliable.

**Comment by richardu** [comment]
@julealgon, great, thanks! It works.

The caveat for this is that Swagger doesn't recognise OData's `EnableLowerCamelCase()` so in order to get Swagger to generate the correct case, I had to decorate the `Id` property with the (otherwise redundant):

`[DataMember(Name = "id")]`.

even though I already call Swagger's equivalent:

`services.AddSwaggerGen(options =>
{
    options.DescribeAllParametersInCamelCase();
}`

Perhaps we should lock the OData, Swashbuckle and Newtonsoft devs in a room together for a while :-)

**Comment by julealgon** [comment]
> The caveat for this is that Swagger doesn't recognise OData's `EnableLowerCamelCase()` so in order to get Swagger to generate the correct case, I had to decorate the `Id` property with the (otherwise redundant):
> 
> `[DataMember(Name = "id")]`.
> 
> even though I already call Swagger's equivalent:
> 
> ```
> services.AddSwaggerGen(options =>
> {
>     options.DescribeAllParametersInCamelCase();
> }
> ```
> 
> Note that the comment on this method is:
> 
> ```
> // Summary:
> // Describe all parameters, regardless of how they appear in code, in camelCase
> ```
> 
> ...so the first letter should definitely be lowercase.

@richardu , the `DescribeAllParametersInCamelCase` method only affects places where Swashbuckle does _not_ use the Json serializer (i.e., everything but the body, like query string, or form data, where it uses built-in "serialization"). Otherwise, it leverages the settings from the Json serializer you have configured.

I imagine you are using the "standard" serializer with Swashbuckle: that is now `System.Text.Json`. You can configure STJ for "camelCase by default" by setting this property:
```csharp
PropertyNamingPolicy = JsonNamingPolicy.CamelCase
```
You can probably easily set this with with a `Configure<JsonSerializerOptions>` call on your startup method. 

Reference:
- https://stackoverflow.com/a/58476761/1946412

However, as per your comment here:
> I'd already replaced System.Text.Json with Newtonsoft.Json in my API before adding OData

You might have already switched Swashbuckle to Newtonsoft as well using https://www.nuget.org/packages/Swashbuckle.AspNetCore.Newtonsoft/. If you didn't, I would recommend doing that for consistency in serialization. A similar setting exists for Newtonsoft.Json to emit everything in camelCase by default.

Again, this would all make a LOT more sense if OData itself leveraged the serializer in the pipeline... then both Swagger and OData would honor the same setting 😞 

> Perhaps we should lock the OData, Swashbuckle and Newtonsoft devs in a room together for a while :-)

I still agree with this, however 🤣

**Comment by richardu** [comment]
@julealgon thx for all of the info!

> A similar setting exists for Newtonsoft.Json to emit everything in camelCase by default.
found and added, thx :-)
