### ISSUE TITLE
@odata.context is missing

### ISSUE THREAD

**Issue by Grauenwolf** [OData/AspNetCoreOData#498]
For some of my OData controllers, the output is missing `@odata.context`. I see it in the Swagger expected result, but not in the actual result. 

### Assemblies affected

* `Microsoft.AspNetCore.OData` 8.0.7

### Reproduce steps

*The simplest set of steps to reproduce the issue. If possible, reference a commit that demonstrates the issue.*

### Expected result

```
{
  "@odata.context": "https://localhost:44323/component-b/odata/$metadata#account",
  "value": [
    {
      "createdOn": "2022-02-15T20:28:58.377Z",
      "accountId": "string",
      "address1Line1": "string",
      "address1City": "string",
      "address1StateOrProvince": "string",
      "address1Country": "string",
      "industryCode": "string",
      "customerSizeCode": "string"
    }
  ]
}
```

### Actual result

```
[
  {
    "$id": "1",
    "createdOn": null,
    "accountId": "65465465",
    "address1Line1": null,
    "address1City": null,
    "address1StateOrProvince": null,
    "address1Country": null,
    "industryCode": null,
    "customerSizeCode": null
  }
]
```

### Additional detail

I have two separate OData models in the same project. One of the models is working fine, the other isn't. 

Things I tried:

* I tried removing the working OData model to see if there was a conflict.
* Changing the order the OData models were added using `AddRouteComponents`.
* Moved an entity from the broken OData model to the working one. (i.e. copied the controller function and EMD setup for that one entity) - The entity works correctly when moved.
* Removed all entities from the broken Odata model except one. (The one that worked when moved to a different model.)
* Renamed the URL for the broken model.

I do not see any errors in the output window when running under a debugger.

Passing in $filter and $top works for both the good and the broken OData model.

I need to fix this so that PowerBI can consume the endpoint.

**Comment by Grauenwolf** [comment]
Blog posts are not the correct place to put important documentation for a library.

**Comment by julealgon** [comment]
> Blog posts are not the correct place to put important documentation for a library.

@Grauenwolf  As long as they are linked in the repo (which they are) I don't see a problem?

Sure, it would probably be a bit better if they were wikis in the repo, but you can still get to the information the same way.

**Comment by Grauenwolf** [comment]
Where in the repository is the link? 

* In the XML docs for the library.
* In the documentation folder mentioned by the Readme for the project.
* Buried in an old issue that they may not even see.

Have the blog posts been updated to reflect the current version of the library? Or do they still say, "Release Candidate", which the reader will interpret as "This may or may not be accurate, reader beware."

Take a look at the documentation folder. Nearly 30% of the files are literally empty.  That's a really bad thing for such an important project.

**Comment by julealgon** [comment]
> Where in the repository is the link?
> - In the XML docs for the library.
> - In the documentation folder mentioned by the Readme for the project.
> - Buried in an old issue that they may not even see.

It's right there in the main readme:
- [1. Introduction](https://github.com/OData/AspNetCoreOData#1-introduction)

![image](https://user-images.githubusercontent.com/461579/155762901-d70ec3c5-c619-4460-8222-ca2e2277cda0.png)

I don't know about you, but the project readme is by far the first place to look for documentation on a library, at least for libraries which don't have a dedicated website (say, like Fluent Validation).

**Comment by julealgon** [comment]
@VladDerptastic would you mind sharing your controller code (or a small sample of it)? It seems like you are getting 2 route registrations: one raw MVC and one OData... that's bad and I'm pretty sure its because of the conventions kicking in alongside the attribute routes... just wanted to confirm.

Probably related:
- https://github.com/OData/AspNetCoreOData/issues/428
- https://github.com/OData/AspNetCoreOData/issues/431

If that's what's going on... I'd probably recommend disabling the conventions if you want to focus only on explicit attribute-routed actions: I find it makes things less confusing. That's a personal take though so take with a grain of salt.

Also, keep in mind that "$select", "$filter" etc will still work even without the route being detected as a "full" OData route. The output is not OData-formatted though as you saw. That's by design to support the "EDM-less" flow. So no surprise there.

**Comment by VladDerptastic** [comment]
Hey @julealgon from the time I posted this to now, there's been plenty of changes to it, but I'm pretty sure you're right, and I can see that in the $odata debug page (from the ODataDebugMiddleware):
![image](https://github.com/OData/AspNetCoreOData/assets/17119930/89c72bf5-66fe-4cc3-ba1c-43fca0f8dcce)

I get duplicates on most base endpoints - one conventional and one not. The endpoints are in controllers inheriting from ODataController and it's one endpoint decorated with [HttpGet] that seems to be getting duplicated. Even though I seem to have enforced the 'odata structure', so it does seem to produce an @odata.context in its results at all cases.

**Comment by aliriocastro** [comment]
> Solution 4: Missing a call to `builder.EntitySet<EntityType>(route);` in the EDM model creation.
> 
> Symptons are similar, but only affect the entity that is missing the `EntitySet` call.

I want to add Solution 5 since I was having the same issue:

**Solution 5:**
Make sure that the returned type matches with the type you specified in the Model Builder. If your method signature returns `IActionResult` the compiler is unable to check the returned type wrapped in `return Ok()`.

If the object returned doesn't match with the one specified in the EdmModel, the returnes JSON won't be formatted with the @odata.context.

**Comment by heitorgiacomini** [comment]
i would ad that change property name also result in context missing.
