### ISSUE TITLE
$expand with Key based query supported?

### ISSUE THREAD

**Issue by groogiam** [OData/AspNetCoreOData#520]
I cannot get the expand to work with this syntax

https://localhost:51992/odata/MyEntity(100)?$expand=SubEntity

Is this intended to be supported. Below is my Get method. Looking at this it seems like the query would already have been evaluated so its probably not supported. Can you confirm or do I have an issue with my Get action? Thanks for your help.

```csharp
 [HttpGet("{key}")]
        [EnableQuery]
        public async Task<IActionResult> Get(long key)
        {
            var retval = _db.MyEntity.FirstOrDefaultAsync(f => f.Id == key);

            if (retval != null)
            {
                return Ok(retval);
            }

            return NotFound();
        }
```

**Comment by julealgon** [comment]
@groogiam if you materialize the results with `FirstOrDefault`, there is no way for OData to expand the query for you. Keep in mind that `EnableQuery` runs _after_ your controller action executes, and you have already returned from the DB at that point in your code.

To support expansion, return an `IQueryable`-based `SingleResult` (an OData type), or return the `IQueryable` directly instead. I recommend the former since it automatically takes care of returning 404 if empty.

**Comment by groogiam** [comment]
@julealgon Thanks for the tip. Is there an example of using this somewhere. I am using it like this but for some reason this does not output odata.context on the response which breaks all my simple odata client calls.

```csharp
[HttpGet("{key}")]
        [EnableQuery]
        public SingleResult Get(long key)
        {
            return SingleResult.Create(Get().Where(w => w.Id == key));
        }
```

**Comment by groogiam** [comment]
@julealgon Disregard my last question, just had to wrap it in an Ok. Thanks for your help.

**Comment by broomfn** [comment]
I'm seeing exactly the same using OData 8, but I've followed the tutorials and they seem to recommend using SingleOrDefault?

https://learn.microsoft.com/en-us/odata/webapi-8/tutorials/basic-crud?tabs=net60%2Cvisual-studio-2022%2Cvisual-studio%2Cvs2022

Any help greatly appreciated.

**Comment by julealgon** [comment]
> I've followed the tutorials and they seem to recommend using SingleOrDefault?

That is sad to see.
