### ISSUE TITLE
How to change select query on server side?

### ISSUE THREAD

**Issue by Criperum** [OData/AspNetCoreOData#555]
Hello
When  I use $select query on Odata it is translated into some elaborate set of ISelectExpandWrapper descendants (that are all internal). I'd like to add additional select fields in some business cases, but it will require to rebuild the whole expression tree. Is there any way to do it?

An example:
In EDM i have a navigation property. In relation DB I need a foreign key to create a link. To avoid duplication of data I make conventional EDM builder to ignore this property so in model clients can see only navigation property.

But when I expand this property i need this property added to Select() expression to be able to later query related entity.

**Comment by julealgon** [comment]
I have a feeling that what you are attempting to do is a bad idea to begin with. Conditionally hiding properties and then having them show up later in the same models without them showing in EDM seems like a recipe for confusion and Principle of Least Astonishment violation.

While I'd recommend you don't do this, I can see 2 simple ways of manipulating OData output that you might want to consider:
1. Decoupling DB models from OData models using something like AutoMapper projections
I've used this before to move away from "poor modeling" on the database side. It allows you to have different views on the API surface compared to what is exposed by EF for example. You then make all queries etc on this external viewmodel layer instead of making them on top of EF entities.

2. Manually handling `ODataQueryOptions<T>` in controllers and then adding `Select` statements on a per-action basis
This gives one pretty much full control over what OData will apply to your underlying data. You can inspect any of the components, modify them, add to them, etc, and then apply to your data.

Obviously these are not "generic" solutions: meaning you'd need to add code to each situation. I'm not sure of any way to do this in a generic manner, but again, I would also not recommend going down that road in the first place.

**Comment by julealgon** [comment]
> That's not what i meant. I don't want to hide props from EDM on condition.

I did not say you were hiding from EDM on condition, but that you "show the value in some places but not in others", while still saying in the EDM that this property doesn't exist. This is massively confusing to a consumer.

> To avoid duplication of data I make conventional EDM builder to ignore this property

I don't quite understand what "duplication" you are talking about here to be honest. IMHO, in your attempt to "simplify" the API you are actually making it significantly more complicated.

Also, the fact that you are consuming things from 2 distinct databases feels bad to me. Instead, I'd have this application have its own database, with data from both other systems it needs to perform its job, and then expose _that_. No hacks needed in that case.

Don't get me wrong, I understand if those are not the answers you are looking for, so I'll stop here.

**Comment by KenitoInc** [comment]
@Criperum 
You can inject your custom implementation of the `SelectExpandBinder`.
First option: 
```csharp
public class MySelectExpandBinder : ISelectExpandBinder
{ 
} 
```
Second option: 
```csharp
public class MySelectExpandBinder : SelectExpandBinder
{ 
}
```
In the `ConfigureServices` method of `Startup.cs`
```csharp
public void ConfigureServices(IServiceCollection services) 
{ 
    services.AddControllers() 
        .AddOData(opt => opt.Count() 
        .Filter() 
        .Expand() 
        .Select() 
        .OrderBy() 
        .SetMaxTop(5) 
        .AddRouteComponents( 
            "odata", 
            GetEdmModel(), 
            svcs => { 
                svcs.AddSingleton<ISelectExpandBinder, MySelectExpandBinder>(); 
        })); 
}  
```

**Comment by Criperum** [comment]
Thank you. That looks very promising. It seems being used in ODataController somewhere. Can I inject this somehow into ODataQueryOptions so I can get Expression through ApplyTo with my implementation used and then explore it?

**Comment by KenitoInc** [comment]
@Criperum Which version of `Microsoft.AspNetCore.OData` are you using?
`SelectExpandBinder` is public for the latest version `v8.0.8`

**Comment by julealgon** [comment]
Can we move this to discussions?

**Comment by Criperum** [comment]
> 

You are right it is now. So If is have a DI container it will replace current SelectExpandBinder with whatever ISelectExpandBinder implementation I set?

**Comment by julealgon** [comment]
> So If is have a DI container it will replace current SelectExpandBinder with whatever ISelectExpandBinder implementation I set?

It's not exactly like that. Notice from @KenitoInc 's example that he is registering the service at a different spot. That's because OData uses its own internal container.

If you don't share the container (which is the default behavior), you can't just register the type outside: it won't be picked up. Follow the example above and it should work fine however.

**Comment by Criperum** [comment]
Is it possible to set IServiceCollection for ODataQueryOptions directly? Outside from ASP Framework for testing purposes (in console app for example)

**Comment by Criperum** [comment]
I've used some example code to work with SelectExpandBinder
`
IServiceCollection services = new ServiceCollection();
services.AddSingleton<ISelectExpandBinder, MySelectExpandBinder>();
services.AddSingleton<IFilterBinder, FilterBinder>();
services.AddSingleton<IOrderByBinder, OrderByBinder>();
var serviceProvider = services.BuildServiceProvider();

ODataQueryOptions<Model2> opts = new ODataQueryOptions<Model2>
    (
    context,
    BuildRequest
                (
                    new DefaultHttpContext()
                    {
                        RequestServices = serviceProvider
                    }.Request,
                    new Uri(BASEADDRESS + queryString)
                )
    );

`

But the ISelectExpandBinder doesn't seem to be injected. How can I set service provider for ODataQueryOptions without ASP framework (in Console App for example)?

**Comment by KenitoInc** [comment]
Hey @Criperum 
For further discussion, open a discussion [here](https://github.com/OData/AspNetCoreOData/discussions)

Closing this issue for now
