### ISSUE TITLE
Unable to return file stream through OData Action with Complex type with Stream property

### ISSUE THREAD

**Issue by ShravyaKusuma** [OData/AspNetCoreOData#593]
**Problem**

I have an OData Action which returns a Complex type with Stream type property.

Seeing the below issue in the response while trying to get the stream as response through a Complex type with Stream type property
Error: "An ODataPrimitiveValue was instantiated with a value of type 'System.IO.FileStream'. ODataPrimitiveValue can only wrap values which can be represented as primitive EDM types."

**Edm Model:**

       <ComplexType Name="DownloadFileBundle">
                <Property Name="ZipStream" Type="Edm.Stream" Nullable="false" />
       </ComplexType>

       var fileConfig = oDataConventionModelbuilder.EntityType<OutputFileEntity>();
       fileConfig.Collection.Action("Download").Returns<DownloadFileBundle>()
                                      .CollectionParameter<string>("fileIds");

**ODataController:**

        public IHttpActionResult Download(ODataActionParameters parameters)
        {
            
                var fileIds = parameters["fileIds"] as IEnumerable<string>;
                IEnumerable<Navigation> navigationTargets = Request.ODataProperties().GetNavigationTargets();
                IOutputFile bll = ServiceLocator.Current.GetInstance<IOutputFile>();
                var fileName = bll.DownloadFiles(navigationTargets, fileIds);

                Stream fileStream = new FileStream(fileName, FileMode.Open, FileAccess.ReadWrite, FileShare.None, 1000, 
                                                          FileOptions.DeleteOnClose);
                var downloadFileBundle = new DownloadFileBundle();
                downloadFileBundle.ZipStream = fileStream;
                return Ok(downloadFileBundle);
         }

**Data Model**

    
    [DataContract(Namespace = EntityNamespaces.BaseServiceNamespace, Name = "DownloadFileBundle")]
    public class DownloadFileBundle : FileBundle
    {
        [DisplayName("File Stream")]
        [DataMember, Required]
        public Stream ZipStream { get; set; }

    }

**Request/Response**

Request:
     
     A Post Request with URI : http://baseUri/OutputFiles/Com.V1.Download
     Body: 

              {
                 "fileIds": ["0AC2F5D0-E35D-4DBE-99B2-4BCE875DD417"]
              }
Response:

    {
    "error": {
        "code": "",
        "message": "An ODataPrimitiveValue was instantiated with a value of type 'System.IO.FileStream'. ODataPrimitiveValue can only wrap values which can be represented as primitive EDM types."
       }
    }

**Additional context**

The functionality is to send the collection of fileIds from the Client (both Desktop & Web) and return a zip of the files corresponding to the fileIds as response.

**Comment by corranrogue9** [comment]
Hey there, in the OData standard, the behavior for a stream property value in a payload is undefined. From the [standard](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#_Toc31358992):

> The values for stream properties do not usually appear in the entity payload. Instead, the values are generally read or written through URLs.

This means that, for your action, there is no way to return the stream as a property of a complex type, and there is no way for the caller to reference the complex type through a URL. You might want to change your action to return `Edm.Stream` directly instead of a complex type. It might also make sense for your case to use `Edm.Binary` instead. This would not have the benefits of streaming, but it would allow the value to be a property on a complex type. You could also potentially change from a complex type to an entity type so that the caller can reference the entity without the action and retrieve the stream that way.

**Comment by corranrogue9** [comment]
I'm going to close this issue since there's currently no action for the OData team to take. Feel free to reach out if you have difficulty with the above options.
