### ISSUE TITLE
ArgumentException with ulong enum

### ISSUE THREAD

**Issue by RichardD2** [OData/AspNetCoreOData#629]
**Assemblies affected**
Microsoft.OData.ModelBuilder v1.0.9

**Describe the bug**
The `ODataConventionModelBuilder` throws an exception if the model contains an enum based on the `ulong` type if the value of any members is larger than `long.MaxValue`.

**Reproduce steps**
* Create a new .NET 6 console app.
* Add a reference to `Microsoft.OData.ModelBuilder` v1.0.9;
* Add the data model (below);
* Add the following code:

```csharp
ODataConventionModelBuilder builder = new();
builder.AddEnumType(typeof(TestEnum));
IEdmModel model = builder.GetEdmModel();
```

**Data Model**
```csharp
public enum TestEnum : ulong
{
    All = ulong.MaxValue,
}
```

**Expected behaviour**
The model should be created.

**Actual behaviour**
An exception is thrown:
> System.ArgumentException: 
> The value of enum member 'All' cannot be converted to a long type. (Parameter 'value')
>   at Microsoft.OData.ModelBuilder.Helpers.EdmTypeBuilder.CreateEnumTypeBody(EdmEnumType type, EnumTypeConfiguration config)
>   at Microsoft.OData.ModelBuilder.Helpers.EdmTypeBuilder.CreateEdmTypeBody(IEdmTypeConfiguration config)
>   at Microsoft.OData.ModelBuilder.Helpers.EdmTypeBuilder.GetEdmTypes()
>   at Microsoft.OData.ModelBuilder.Helpers.EdmTypeBuilder.GetTypesAndProperties(IEnumerable`1 configurations)
>   at Microsoft.OData.ModelBuilder.Helpers.EdmModelHelperMethods.BuildEdmModel(ODataModelBuilder builder)
>   at Microsoft.OData.ModelBuilder.ODataConventionModelBuilder.GetEdmModel()

**Comment by gathogojr** [comment]
@RichardD2 Thank you for reporting this issue. We triaged a [similar issue](#596) not so long ago. The `ulong` type is not supported by the standard. We don't explicitly forbid it's use. However, we [internally just map it to a long](https://github.com/OData/ModelBuilder/blob/main/src/Microsoft.OData.ModelBuilder/Commons/EdmLibHelpers.cs#L92-L93) in the model builder logic. That's why an exception is thrown whenever you try to use a value that exceeds `int.MaxValue`
