### ISSUE TITLE
Unexpected behavior: Adding alternate key route also creates a query param endpoint

### ISSUE THREAD

**Issue by CharlesSchimmel** [OData/AspNetCoreOData#649]
**Assemblies affected**
 ASP.NET Core OData 8.x

**Describe the bug**
Adding an alternate key route `odata/Example(Name={name})` also implicitly creates an endpoint at `odata/Example` with a query parameter for `Name`. This is unexpected and in my use case causes an issue with API documenting tools like Swagger having difficulty with identical routes that have different parameters. Swagger has methods for resolving this conflict but the real issue is that an endpoint is being created that's not visible to the developer.

**Reproduce steps**
This has been extracted and simplified from my actual project (entity renamed, etc). I can pull it into its own project if it's helpful.

```c# Program.cs
// Program.cs
var builder = WebApplication.CreateBuilder(args);
builder.Services.AddOdata(options => options.AddRouteComponents("odata", GetEdmModel()));
```
```c# EdmModel.cs
// EdmModel.cs
public static IEdmModel GetEdmModel() {
        builder.EntitySet<Example>(nameof(Example));
        builder.EntityType<Example>()
            .HasAlternateKeys(altKeyConfig => altKeyConfig.HasKey(propertyRefConfig => propertyRefConfig.HasName(new EdmPropertyPathExpression(nameof(Example.Name)))));
        var model = builder.GetEdmModel();
        // same issue with this syntax
        //var examples = model.SchemaElements.OfType<IEdmEntityType>().First(c => c.Name == nameof(Example));
        //var name = examples.FindProperty(nameof(Example.Name).ToLower());
        //model.AddAlternateKeyAnnotation(examples, new Dictionary<string, IEdmProperty>
        //{
        //    {"Name", name},
        //});
        return model;
}
```
```c# ExampleController.cs
// ExampleController.cs
[ProducesResponseType(StatusCodes.Status400BadRequest, Type = typeof(string))]
[ProducesResponseType(StatusCodes.Status401Unauthorized)]
[ProducesResponseType(StatusCodes.Status500InternalServerError)]
public class ExampleController : ODataController
{
    private readonly IExampleRepository _exampleRepository;

    public ExampleController(IExampleRepository uow)
    {
        _exampleRepository = uow;
    }

    [EnableQuery]
    [ProducesResponseType(typeof(ODataResponse<Example>), StatusCodes.Status200OK, MediaTypeNames.Application.Json)]
    public IActionResult Get()
    {
        return Ok(_exampleRepository.GetAll());
    }

    [HttpGet("odata/Examples(Name={exampleName})")]
    [ProducesResponseType(typeof(ODataResponse<Example>), StatusCodes.Status200OK, MediaTypeNames.Application.Json)]
    public IActionResult Get([FromRoute] string exampleName)
    {
        var query = _exampleRepository
            .Query()
            .Where(c => c.Name == exampleName);

        if (!query.Any())
            return NotFound($"Cannot find Example with Name: {exampleName}.");

        return Ok(query);
    }
}

```

**Data Model**
```c# Example.cs
public class Example {
    public Guid Id {get;set;}
    public string Name {get;set;}
}
```

**EDM (CSDL) Model**
Can be provided if needed.

**Expected behavior**
Adding an alternative key route adds only the one endpoint.

**Comment by julealgon** [comment]
Can you share the output of the $odata debug endpoint?

**Comment by CharlesSchimmel** [comment]
### OData Endpoint Mappings

Controller & Action | HttpMethods | Template
-- | -- | --
ExampleProject.OData.ExamplesController.Get   (ExampleProject) | GET | odata/Examples
ExampleProject.OData.ExamplesController.Get   (ExampleProject) | GET | odata/Examples/$count
ExampleProject.OData.ExamplesController.Get   (ExampleProject) | GET | odata/Examples
ExampleProject.OData.ExamplesController.Get   (ExampleProject) | GET | odata/Examples/$count
Microsoft.AspNetCore.OData.Routing.Controllers.MetadataController.GetMetadata   (Microsoft.AspNetCore.OData) | GET | odata/$metadata
Microsoft.AspNetCore.OData.Routing.Controllers.MetadataController.GetServiceDocument   (Microsoft.AspNetCore.OData) | GET | odata

### Non-OData Endpoint Mappings
Controller | HttpMethods | Template
-- | -- | --
ExampleProject.AliveController.GetAlive   (ExampleProject) | GET | Alive
ExampleProject.ExamplesController.CreateOrReplace   (ExampleProject) | PUT | Examples/{exampleName}
ExampleProject.OData.ExamplesController.Get   (ExampleProject) | GET | odata/Examples(Name={exampleName})

**Comment by julealgon** [comment]
Seems like the first problem you have is that the route you created is not being detected as an actual OData route. I've never used alternate keys so I don't know how to help with that.

Second issue is probably caused by the convention + explicit attributes strategies finding the same endpoints and creating duplicate entries. You can either rename your controller actions so they don't match the convention anymore and only use explicit routes, or you can just disable the convention strategy altogether and only rely on explicit routes. I don't know of a "clean" way of removing the convention strategy besides just manipulating the conventions list during setup though.

I believe this issue I created some time ago describes the problem you are seeing there with duplicate endpoints:
- https://github.com/OData/AspNetCoreOData/issues/431

**Comment by xuzhg** [comment]
@julealgon Thanks for following up.

@CharlesSchimmel Please allow me to explain:

1)  `HasAlternateKeys` in  `builder.EntityType<Example>()
            .HasAlternateKeys(altKeyConfig => altKeyConfig.HasKey(propertyRefConfig => propertyRefConfig.HasName(new EdmPropertyPathExpression(nameof(Example.Name)))));`  is a new API added to add the alternate key using `Org.OData.Core.V1.AlternateKeys`, you can send $metadata to verify

```xml
<Annotation Term="Org.OData.Core.V1.AlternateKeys">
  <Collection>
    <Record>
      <PropertyValue Property="Key">
      <Collection>
        <Record>
          <PropertyValue Property="Name" PropertyPath="Name"/>
         </Record>
     </Collection>
    </PropertyValue>
   </Record>
   </Collection>
  </Annotation>
</Annotations>
```

To be noted, `Org.OData.Core.V1.AlternateKeys` is not supported in the URI parser in OData.net lib. So, we can't "understand" it and use it to build the OData path.

2) So, you should use `AddAlternateKeyAnnotation` extension method to add the `OData.Community.Keys.V1.AlternateKeys`



Your codes have some problems, here's the working version:
```C#
         // remember to comment the following line out
         //   builder.EntityType<Example>()
          //      .HasAlternateKeys(altKeyConfig => altKeyConfig.HasKey(propertyRefConfig => propertyRefConfig.HasName(new EdmPropertyPathExpression(nameof(Example.Name)))));
           var model = builder.GetEdmModel() as EdmModel;
            //same issue with this syntax
            var examples = model.SchemaElements.OfType<IEdmEntityType>().First(c => c.Name == nameof(Example));
            var name = examples.FindProperty(nameof(Example.Name));
            model.AddAlternateKeyAnnotation(examples, new Dictionary<string, IEdmProperty>
            {
                {"Name", name},
            });
```

With this change, you can get the following:

![image](https://user-images.githubusercontent.com/9426627/181107814-7df9ef01-1f87-4fe6-80ae-276256d57d65.png)



3) Your [HttpGet] also has a problem, where `Examples` is not a valid entity set. Because you build the model using the `Example`. So `[HttpGet("odata/Example(Name={exampleName})")]`  should work. ( Example (without s) is the entity set).

4) Now, you can have the following endpoints:

![image](https://user-images.githubusercontent.com/9426627/181108272-0c5c9f32-d5bb-4988-a834-40aec89def86.png)

**To be noted**:  we also build `~/odata/Example ` and `~/odata/Example/$count` for the second `Get` action. This is because:

`public IActionResult Get()` and `public IActionResult Get(string exampleName)` are the same at OData conventional routing (We ignore **unknown** parameter `exampleName` in this case).

So, if you don't want us to build `~/odata/Example ` and `~/odata/Example/$count`, you can rename the action (any name, but not Get), for example

`public IActionResult GetByAlternateKey(string exampleName)`

**Comment by CharlesSchimmel** [comment]
Thanks for the quick and comprehensive responses @julealgon and @xuzhg ! This is working for me now and maps the routes correctly. I don't think it matters, but I'll note that (3) was a transcription error in my example, the actual problematic route was aligned with the entity set name.

**Comment by xuzhg** [comment]
@CharlesSchimmel you are welcome! let us know if you have more questions/concerns. Thanks.
