### ISSUE TITLE
The new JSON writer

### ISSUE THREAD

**Issue by m1borisov** [OData/AspNetCoreOData#668]
Hi, I'm trying to use new JSON writer based on Utf8JsonWriter (from https://devblogs.microsoft.com/odata/using-the-new-json-writer-in-odata/). I added additional requried configuration lines in startup methods:

```
builder.Services.AddControllers()
    .AddOData(options =>
        options.AddRouteComponents("odata", new ODataConventionModelBuilder().GetEdmModel(), services =>
        {
            services.AddSingleton<IStreamBasedJsonWriterFactory>(_ => DefaultStreamBasedJsonWriterFactory.Default);
        })
        .EnableQueryFeatures(1000)); 
```
But after measuring the results and performance, I did not notice any changes and decided to look deeper. I created custom `IStreamBasedJsonWriterFactory` implementation:
```
public class CustomStreamBasedJsonWriterFactory : IStreamBasedJsonWriterFactory
{
    public IJsonWriterAsync CreateAsynchronousJsonWriter(Stream stream, bool isIeee754Compatible, Encoding encoding)
    {
        return DefaultStreamBasedJsonWriterFactory.Default.CreateAsynchronousJsonWriter(stream, isIeee754Compatible, encoding);
    }

    public IJsonWriter CreateJsonWriter(Stream stream, bool isIeee754Compatible, Encoding encoding)
    {
        return DefaultStreamBasedJsonWriterFactory.Default.CreateJsonWriter(stream, isIeee754Compatible, encoding);
    }
}
```
Also I updated services configuration with changing `services.AddSingleton<IStreamBasedJsonWriterFactory>(_ => DefaultStreamBasedJsonWriterFactory.Default);` to `services.AddSingleton<IStreamBasedJsonWriterFactory, CustomStreamBasedJsonWriterFactory>();`. I decided to debug the custom factory and added breakpoints to each Create* method, but they are not triggered on requests for any odata controller action.
I used Microsoft.AspNetCore.OData 8.0.11 with two different target framewoks (netcoreapp3.1 and net6.0), but the results are same.
Could you tell me if this is an issue or am I doing something wrong?

**Comment by julealgon** [comment]
> I decided to debug the custom factory and added breakpoints to each Create* method, but they are triggered on requests for any odata controller action.

Did you mean 
> ...they are **not** triggered...

?

**Comment by xuzhg** [comment]
@habbes

**Comment by m1borisov** [comment]
@julealgon yes, not triggered, thanks

**Comment by habbes** [comment]
Thanks for reporting this @m1borisov. Let me investigate and get back to you.

**Comment by julealgon** [comment]
@m1borisov are you sure the endpoints you are working with are actually OData endpoints? Can you show us the output of the `$odata` debug middleware?

Your example is showing an empty EDM model, so this is why I'm curious here. AFAIK, none of the OData serialization services will be used if your endpoint is being detected as a standard MVC endpoint.

Feel free to post sample controller code, as well.

**Comment by m1borisov** [comment]
yes, here is the contoller code:
```
[ApiController]
[Route("[controller]")]
public class WeatherForecastController : ControllerBase
{
    private readonly IWeatherForecastService weatherForecastService;

    public WeatherForecastController(IWeatherForecastService weatherForecastService)
    {
        this.weatherForecastService = weatherForecastService;
    }

    [EnableQuery]
    [Route("forecasts")]
    public IQueryable<WeatherForecast> GetWeatherForecasts()
    {
        return weatherForecastService.GetAllHistory();
    }
}
```
And my request example url: `/weatherforecast/forecasts?$top=3&$filter=temperatureC le 0`, filter and top selection work correctly, so I think that OData processes my request.

**Comment by julealgon** [comment]
> And my request example url: `/weatherforecast/forecasts?$top=3&$filter=temperatureC le 0`, filter and top selection work correctly, **so I think that OData processes my request.**

This is not necessarily the case. Not entirely, at least.

You see, OData actually has 2 "operation modes" (I'm coming up with these terms, don't quote me 😆 ): "pure OData", and "OData-ready". The former relies on an EDM model, and emits payloads that are compatible with the OData spec (with all the extra odata-specific attributes in the json, the content-type, etc). The latter though is just "adding some OData-like query support to existing MVC endpoins". I've heard of the term "EDM-less" before, as well, to describe this.

EDM-less OData has quite a few restrictions, since a lot of the functionality requires the EDM model behind the scenes.

I believe what you are seeing here is the latter case. You've added `[EnableQuery]` which activates filtering capabilities, but your endpoint is still a standard MVC endpoint, and thus serialized using standard MVC classes (i.e. it completely bypasses the OData serialization pipeline).

Once you change your code to the "pure OData" mode, your custom implementation _should_ start to be used. For that, you have to make sure you have a matching EDM model initialized (one that has at least one entityset matching your controller), and that the route you are defining aligns with this model.

You can check the "alignment" by looking into the route debug results as @habbes detailed above. If your route shows as non-OData, you shouldn't expect that any of the OData-specific serialization classes will be active.

**Comment by m1borisov** [comment]
The route debug table showed that my action was non-OData endpoint. After adding the EDM model:
```
private static IEdmModel GetEdmModel()
{
    var builder = new ODataConventionModelBuilder();
    builder.EntitySet<WeatherForecast>("WeatherForecast")
        .EntityType
        .HasKey(x => x.Id);
    return builder.GetEdmModel();
}
```
and renaming the action from `GetWeatherForecasts` to `Get` the new OData enpoint appired in the table. Now the `IStreamBasedJsonWriterFactory` implementation works, thanks.

**Comment by habbes** [comment]
Thanks @julealgon @m1borisov. Closing this issue as resolved.
