### ISSUE TITLE
Batch response contains invalid JSON when using DefaultStreamBasedJsonWriterFactory

### ISSUE THREAD

**Issue by andygjp** [OData/AspNetCoreOData#673]
**Assemblies affected**

Microsoft.AspNetCore.OData v8.0.11

**Describe the bug**

After updating the package and enabling the `IStreamBasedJsonWriterFactory`, according to the blog post: https://devblogs.microsoft.com/odata/using-the-new-json-writer-in-odata/#odata-web-api-8-x, batch responses produce invalid JSON - the body is in the wrong place (see response below).

**Reproduce steps**

1. Update Microsoft.AspNetCore.OData to v8.0.11. 
2. Configure your route with `DefaultODataBatchHandler`.
3. Make a batch request.
 
```csharp
options.AddRouteComponents("api", EdmModelBuilder.GetEdmModel(), routeServices =>
{
    routeServices.AddSingleton<ODataBatchHandler, DefaultODataBatchHandler>();
    routeServices.AddSingleton<IStreamBasedJsonWriterFactory>(_ => DefaultStreamBasedJsonWriterFactory.Default);
});
```

**Request**

```text
POST http://localhost:5000/api/$batch
Content-Type: application/json
```

```json
{
  "requests": [
    {
        "id": "1",
        "method": "POST",
        "url": "SalesProducts",
        "headers": {
          "content-type": "application/json"
        },
        "body": {
            "ProductCode": "FHDKSN,
            "ShortDescription": "Product",
            "ShipSize": "Small",
            "FulfilmentType": "FromWarehouse"
        }
    }
  ]
}
```

**Response**

```text
HTTP/1.1 200 OK
Content-Type: application/json
Date: Wed, 24 Aug 2022 17:18:02 GMT
Server: Kestrel
Transfer-Encoding: chunked
Vary: Accept-Encoding
OData-Version: 4.0
```

```json
{
  "responses": [
    {
      "id": "1",
      "status": 201,
      "headers": {
        "location": "http://localhost:5000/api/SalesProducts(52)",
        "content-type": "application/json; odata.metadata=minimal; odata.streaming=true; charset=utf-8",
        "odata-version": "4.0"
      },
      "body":
    }
  ]
}{
  "@odata.context": "http://localhost:5000/api/$metadata#SalesProducts/$entity",
  "@odata.etag": "W/\"dmVyc2lvbicyNDg3Jw==\"",
  "ShortDescription": "FHDKSN",
  "ProductCode": "Product",
}
```

**Expected behavior**

It should produce valid JSON, ie the `"body"` member should contain the body instead of being at the end of a response.

**Additional context**

If the request contains two or more requests, the first request always has its body in the wrong place and the other requests are fine.

**Comment by andygjp** [comment]
I've created a basic sample to demonstrate the issue:

https://github.com/andygjp/NewODataJsonWriterProducesInvalidResponse

**Comment by habbes** [comment]
Thanks @andygjp for reporting this issue. And thanks for sharing a repro project. We have been able to reproduce the issue and determine the root cause.

The issue is that `ODataUtf8JsonWriter` is not writing to the same stream as the batch handler. When writing an asynchronous message, the `ODataJsonLightOutputContext` creates a [`BufferedStream`](https://github.com/habbes/odata.net/blob/odataurislim-class-experiment/src/Microsoft.OData.Core/JsonLight/ODataJsonLightOutputContext.cs#L101) that wraps the message stream. This`BufferedStream` is what should be used as the output stream. The "old" JsonWriter uses this buffered stream as the output stream. But the new writer [uses the underlying message stream directly](https://github.com/habbes/odata.net/blob/odataurislim-class-experiment/src/Microsoft.OData.Core/JsonLight/ODataJsonLightOutputContext.cs#L117).

The batch handler does not use the JSON writer to write the body if a sub-request to the main response body, it uses Stream.CopyTo directly to copy the contents of the inner request's response to the main response body. The rest of the metadata are written using the JSON writer. Since the body is copied directly, it's written to the `BufferedStream`. These contents remain in the buffer until flushed, meanwhile the other properties get written. The stream is flushed before writing the next request's body. So as a result, the first request's body is written at the second's request body position, and so on and so forth. And the last request's body is written at the end, after everything else.

We're working on a fix.
