### ISSUE TITLE
`$search` is not applied to MVC action result nor when using ODataQueryOptions.ApplyTo

### ISSUE THREAD

**Issue by cdavernas** [OData/AspNetCoreOData#696]
**Assemblies affected**
Which assemblies and versions are known to be affected e.g. ASP.NET Core OData 8.x

**Describe the bug**
`$search` is **not** applied to MVC action results nor is applied when using `ODataQueryOptions.ApplyTo`. The only way to make it work is to contact the ODATA endpoints. All other clauses are applied to all other actions marked with the `EnableQuery` attribute (with all QueryOptions allowed).

**Reproduce steps**
Execute a search query on one of your MVC Controller actions marked with the `EnableQuery` attribute.

**Expected behavior**
The `$search` clause to be applied to action results of MVC actions marked with the `EnableQuery` attribute. Ideally, the `ODataQueryOptions.ApplyTo` method should also apply the search clause.

**Comment by corranrogue9** [comment]
Because there is no direct mapping of `$search` to a LINQ expression and the OData standard allows for customization of the `$search` option, `ApplyTo` is not able to have a deterministic implementation for *how* to apply the query option. Because of this, it is by design that the controller needs to implement this logic for itself. The parsed search expression is available in the query options so that the controller can more easily apply its own logic.
