### ISSUE TITLE
$top is not giving an error in $expand when its value is greater than MaxTop

### ISSUE THREAD

**Issue by KwizaKaneria** [OData/AspNetCoreOData#707]
I set Maxtop=100 on the controller. When I send /odata/state?$top=200, it gives the following error.

Error: The query specified in the URI is not valid. The limit of '100' for the Top query has been exceeded. The value from the incoming request is '200'.

But when I send /odata/state?$exapnd=counties($top=200) then it did not give an error.

Can you please guide us on this issue? Is this expected behavior or not?

**Comment by julealgon** [comment]
> Is this expected behavior or not?

I believe it is.

@KwizaKaneria `MaxTop` should apply independently to each entity. Since you configured this at the `[EnableQuery]` attribute, it will apply to the entity on the controller, which is `State`.

Try adding a `MaxTop` configuration in the EDM, on the `Country` entity type, and see if that works for you.

**Comment by julealgon** [comment]
@KwizaKaneria I see you closed this. Just wanted to double check that configuring in the EDM level worked for your needs.
