### ISSUE TITLE
$count in $filter expression doesn't work

### ISSUE THREAD

**Issue by SEnglishSMP** [OData/AspNetCoreOData#74]
According to the [section 4.8 of the OData v4.01 URL Conventions spec](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part2-url-conventions.html#sec_AddressingtheCountofaCollection), the following query should be supported:
```
 http://host/service/Categories?$filter=Products/$count gt 0
```
However, attempting this query with an AspNetCoreOData project returns the an error with the following message:
> The query specified in the URI is not valid. Validating OData QueryNode of kind Count is not supported by FilterQueryValidator.

This is a bug that was apparently fixed in the OData Lib (see https://github.com/OData/odata.net/issues/440) but is still an issue here.

**Comment by Leandro-Albano** [comment]
I noticed that this still happening.
Some [unit tests](https://github.com/OData/AspNetCoreOData/blob/master/test/Microsoft.AspNetCore.OData.Tests/Query/FilterQueryOptionTest.cs#L46) exercise this behavior, but the issue seems to be because on [FilterQueryValidator](https://github.com/OData/AspNetCoreOData/blob/master/src/Microsoft.AspNetCore.OData/Query/Validator/FilterQueryValidator.cs#L792) the `QueryNodeKind.Count` falls into the default switch option and throws `NotSupported`.

@xuzhg  I'm opening a PR for this, could you tell me if you see any side effect of changing that?
