### ISSUE TITLE
If $top is not used, the default number of requests is limited

### ISSUE THREAD

**Issue by kinglinglive** [OData/AspNetCoreOData#765]
What should I do when I don't use $top to limit the default number of requests instead of returning all the numbers that can be found

**Comment by julealgon** [comment]
@kinglinglive when you see a repository that has the "Discussions" feature enabled, it is best etiquette to ask these kinds of questions there instead of opening issues.

Search for "server-driven paging" in OData and you should find what you are looking for. You can set paging options in multiple places including in the `[EnableQuery]` attribute if you are using that.

**Comment by xuzhg** [comment]
@kinglinglive 
The client can use $top & $skip to limit the number returning from service. So, it can be considered as client-side pagination.  

You can use 'PageSize' on EnableQueryAttribute at ([here](https://github.com/OData/AspNetCoreOData/blob/main/src/Microsoft.AspNetCore.OData/Query/EnableQueryAttribute.Config.cs#L118))(mentioned as @julealgon ) to config the server side pagination.

let us know if it can't work.
