### ISSUE TITLE
Any way to get DateTime to work?

### ISSUE THREAD

**Issue by Vaccano** [OData/AspNetCoreOData#815]
I know that with the v4 version of the OData spec, one of the people on the committee pushed through a change to remove the `DateTime` type.  For several years we have held on to our WCF DataServices OData services because they run v3 (and thus do not have this limitation).  We now want to host those services in Kubernetes, so we need to get them upgraded to a Linux compatible version.  (ie .Net 6)  This means that all our many applications that use our OData v3 services need to be ready for v4 restrictions.

Before we start a large initiative to update all of our applications to expect `DateTimeOffset` from the OData services, I thought I would ask if there has been any "progress" on this situation?  

I know it is a longshot, but I am hoping there is a flag or something that makes the service support `DateTime` instead of `DateTimeOffset`.

_NOTE: I have **VERY** solid reasons for wanting to use `DateTime` over `DateTimeOffset`.  But since they are not relevant to this question, I am not boring you by posting them here._

**Comment by julealgon** [comment]
Can't version 3 be set in the EDM model builder? Wouldn't that allow you to use v3 in a modern API?

![image](https://user-images.githubusercontent.com/461579/213701610-d4489bfb-188e-41c8-8ba9-672c41954d89.png)

**Comment by xuzhg** [comment]
@Vaccano @julealgon DateTime is a long, tough topic. Since OData v4 moved into OASIS standard, DateTime is removed for its ambiguity. It's recommended to use 'unique' DateTimeOffset. Such a decision makes some customers unable to upgrade their services.

As a workaround, ASP.NET Core OData 7 & 8 do support DateTime (DT) using DateTimeOffset (DTO).  ASP OData will treat DateTime as DateTimeOffset. It means Customers doesn't need to change their model (C# classes). ModelBuilder can build the property with 'System.DateTime' to "Edm.DateTimeOffset". In the serialization/deserialization, DTO is used to replace DT.

Please take a look our tests related to 'Date & Time' at: https://github.com/OData/AspNetCoreOData/tree/main/test/Microsoft.AspNetCore.OData.E2E.Tests/DateAndTimeOfDay

And let me know any further questions.

**Comment by Vaccano** [comment]
@xuzhg - Updating the services to support DateTime would not really be a big issue for us.  We have about 10 OData Services.  Of those only 4 or 5 are heavily used.  We could easily handle an update there.

The problem comes with the applications (aka clients) that use the OData services.  With v4, I am forced to go update all of them to expect DateTimeOffset instead of DateTime.  (Also, while I don't want to get drawn into a debate between DateTime and DateTimeOffset, I will say that our use case does not want the extra precision that is required with DateTimeOffset. )

I knew it was a long shot, but I thought I would check to see if there was a way to allow DateTime to work with OData.  Sounds like the answer is "no".  I am thinking we will have to build some kind of translation layer that will convert the results to have DateTime instead of DateTimeOffset.

**Comment by gathogojr** [comment]
`DateTime` no longer supported based the OData OASIS standard
