### ISSUE TITLE
Lazy load properties

### ISSUE THREAD

**Issue by marcopelegrini** [OData/AspNetCoreOData#850]
Is there a way to lazy load complex types?

If I understand correctly, only EntityTypes are lazy loaded by default, if an Entity has a complex type it will be retuned (or expected to be).
I'm trying to populate a property of a model on demand as it's not database driven. But that doesn't seem to fit in the OData convention.

If I map that property as an Entity (faking an Id for example), then I can use $expand to trigger it's loading. But I do lose the ability to query that property /Entity/LazyLoadedProperty...
If I keep it as a complex type, then I'd have to add a custom query parameter to trigger the load of that property.

Ideally what I'd like is to define it as a complex type and be able to use both

`odata/Entity?$expand=LazyLoadedProperty`
and
`odata/Entity/LazyLoadedProperty`

Any way to accomplish that?

**Comment by xuzhg** [comment]
@marcopelegrini ODL does support querying 'any kind' of property from a single entity.

 So, if 'LazyLoadedProperty' is a navigation property (aka, the property type is entity type), it should work:

1) odata/Entity?$expand=LazyLoadedProperty  (If you enable the OData query options)
2) odata/Entity/LazyLoadedProperty (If you have such endpoint).

 For #  2, be noted, you can't query a single property from a collection. So, if "Entity" is a singleton,  `odata/Entity/LazyLoadedProperty` is valid, otherwise, if "Entity" is a collection (entity set), your endpoint should have key after Entity as `odata/Entity({key})/LazyLoadedProperty`
Of course, if you do NOT want to have a key, you can use the extension to build your own endpoint.

**Comment by marcopelegrini** [comment]
Thanks, I ended up mapping my object as an entity (even though it could've stayed a complex type), and that way I can just have a separate route for it. For now, that suffices!
