### ISSUE TITLE
ODataDynamicModel: Why {entityset}({key}) doesn't work?

### ISSUE THREAD

**Issue by pluc77** [OData/AspNetCoreOData#884]
### Discussed in https://github.com/OData/AspNetCoreOData/discussions/860

<div type='discussions-op-text'>

<sup>Originally posted by **csharp4fun1** March 19, 2023</sup>
Hello,

I tried the ODataDynamicModel because I have to switch from OData 7 to OData 8 and have dynamic data model coming at runtime. 

The example is working basically out of the box. So calling http://[localhost:4527/odata/mydatasource/products](http://localhost:4527/odata/mydatasource/products) is getting me the products where the products are dynamic data. 
https://github.com/OData/AspNetCoreOData/blob/0ab15a448285bb53e4d33a48f0feb6c163699d94/sample/ODataDynamicModel/Controllers/HandleAllController.cs#L30

But the odata endpoint below isn't working. When I try to call http://localhost:4527/odata/mydatasource/products(1) - that means this endpoint here
https://github.com/OData/AspNetCoreOData/blob/0ab15a448285bb53e4d33a48f0feb6c163699d94/sample/ODataDynamicModel/Controllers/HandleAllController.cs#L53
it doesn't go there. 

These examples are also written here on bottom of the page: https://github.com/OData/AspNetCoreOData/tree/main/sample/ODataDynamicModel

Does anyone know why the more detailed endpoints are not working?</div>

**Comment by xuzhg** [comment]
@pluc77 Thanks for trying the sample. 

This is not a bug or a feature gap. It's by implemented because the sample only enables 'key as segment'.

You can see the codes:
https://github.com/OData/AspNetCoreOData/blob/main/sample/ODataDynamicModel/Extensions/EntitySetWithKeyTemplateSegment.cs#L24

If you want to support key in parenthesis, you can add a new `yield` to enable it, like:

<img width="970" alt="image" src="https://user-images.githubusercontent.com/9426627/230466120-5c5132d9-c97e-43e3-ab65-36bf7e8de576.png">

Then, it should work as:

<img width="780" alt="image" src="https://user-images.githubusercontent.com/9426627/230466324-6f1299ce-da17-4509-943d-448f0721b1d6.png">

**Comment by pluc77** [comment]
My bad, Sam. I missed that. Thank you for the quick response!

**Comment by xuzhg** [comment]
> My bad, Sam. I missed that. Thank you for the quick response!

Never mind. You are welcome to file any kind of issues.
