### ISSUE TITLE
"The property does not exist" when using [FromBody] and PUTing Json with extra properties.

### ISSUE THREAD

**Issue by danroot** [OData/AspNetCoreOData#898]
**Assemblies affected**
Microsoft.AspNetCore.OData 8.0.12
Microsoft.AspNetCore.OData.NewtonsoftJson 8.0.12

**Describe the bug**
I am using AspNetCore.OData with NewtonsoftJson.  I have added this to NewtonSoft options:
```o.SerializerSettings.MissingMemberHandling = Newtonsoft.Json.MissingMemberHandling.Ignore; ```
I have an ODataController with a Put method:
``` public virtual async Task<IActionResult> Put([FromODataUri] int key, [FromBody] MyModel update)```
However, if I PUT to this endpoint with JSON that includes members not on the model, then update is null and ModelState contains an error like "The property 'Foo' does not exist."
If I PUT to a non-OData endpoint, then the model is deserialized and there is no ModelState error.

**Reproduce steps**
Create an ODataController and configure NewtonsoftJson.
``` public virtual async Task<IActionResult> Put([FromODataUri] int key, [FromBody] MyModel update){ ... }```
Issue a PUT request for the entity, supplying a member in the JSON that is not on MyModel:
```
{SomeFieldOnMyModel:'test',SomeFieldNotOnMyModel:'should ignore'}
```
Observe SomeFieldNotOnMyModel is not ignored and "update" is null and ModelState contains an error about the missing property.
 
**Data Model**
```
public class MyModel{
    public string SomeFieldOnMyModel{get;set;}
}
```

**Request/Response**
```
PUT /data/MyModel 
{
  SomeFIeldOnMyModel:'test',
  SomeExtraFIeld:'will cause error'
}
```

**Expected behavior**
I would like for it to deserialize MyModel with no ModelState errors even if the Json includes a property not on the model.

I understand the "right" thing to do is to modify the UI to not post incorrect data, but in this case that would be logistically difficult.   Sometimes developers accidentally include members in client code due to databinding, etc.  These should be fixed, but that is logistically difficult in this case. Also, I would expect the API and OData behavior to match.

Is there some way to get it to honor "Newtonsoft.Json.MissingMemberHandling.Ignore" or some other way to tell OData model binding to ignore missing members?

**Comment by xuzhg** [comment]
@danroot it seems you are looking for the open type & dynamic property.

You can simply change your model as:

```C#
public class MyModel{
    public string SomeFieldOnMyModel{get;set;}
    public IDictionary<string, object> Dynamics {get;set;} = new Dictionary<string, object>();
}
```

Then, I think you can retrieve the 'SomeFieldNotOnMyModel' from the dictionary.

To be clear, OData doesn't use 'JSON SerializerSettings' to config the reading/writing.

**Comment by KenitoInc** [comment]
Options include:
- Override OData serializers/deserializers

**Comment by xuzhg** [comment]
> Thanks @xuzhg ! That does indeed solve my immediate problem. It wasn't so much I needed to read the "extra" properties, just that client code added them, causing deserialization to break. Adding the dictionary to the model and marking [NotMapped] for EFCore's sake fixed the issue, and I can just ignore the contents.
> 
> I am confused on that last statement though. I thought that when using Microsoft.AspNetCore.OData.NewtonsoftJson, SerializerSettings such as o.SerializerSettings.ReferenceLoopHandling and o.SerializerSettings.ContractResolver seem to have an effect on serialization. In my case, I have some non-OData APIs and some OData APIs, and want them to share rules about converters, etc. Other 3rd party code (Telerik Reports) forces me to use Newtonsoft instead of System.Text.JSON. What is the correct extension point if did I want to customize JSON serialization/deserialization?

@danroot 
Sorry for the confusing about 'OData doesn't use 'JSON SerializerSettings' to config the reading/writing'. Here what I mean is that: OData library has its own JSON reader and JSON writer to read/write OData payload, it doesn't reply to other JSON libs. 

However, as you mentioned, you have non-OData APIs, you can apply OData queries to non-OData APIs, for example $filter, $expand, $select. And the result is NON-OData payload. In this case, it doesn't go to OData default JSON serialization. By default, it goes to System.Text.JSON serialization. If you want to use Newtonsoft.JSON serialization, as you did, you can use 'Microsoft.AspNetCore.OData.NewtonsoftJson'. 

- Microsoft.AspNetCore.OData contains the default System.Text.JSON converter for non-OData queries, for example [here](https://github.com/OData/AspNetCoreOData/blob/main/src/Microsoft.AspNetCore.OData/Query/Wrapper/SelectExpandWrapperConverter.cs). 
- Microsoft.AspNetCore.OData.NewtonsoftJson contains the Newtonsoft.JSON converter for non-OData queries, for example [here](https://github.com/OData/AspNetCoreOData/blob/main/src/Microsoft.AspNetCore.OData.NewtonsoftJson/JSelectExpandWrapperConverter.cs)

Since, there's no SCENARIOS to "READ" a non-OData payload, for example, which scenarios to read a 'SelectExpand'? , then, all converters only implement the writing logic.

**Comment by danroot** [comment]
Ok, got it. thanks!
